const fs = require('fs');
const path = require('path');
const { execFileSync } = require('child_process');

const DESKTOP = path.resolve(__dirname, '..');
const NSIS_CACHE = path.join(
  process.env.LOCALAPPDATA,
  'electron-builder',
  'Cache',
  'nsis',
  'nsis-3.0.4.1'
);
const MAKENSIS = path.join(NSIS_CACHE, 'makensis.exe');

const PASSWORD = '6324919';
const DEVELOPER = 'تم تصميم وتطوير هذا النظام بواسطة المهندس مصطفى طلعت للحلول البرمجيه - 01116626164';
const APP_NAME = 'MTE Systems';
const VERSION = '1.0.0';
const WIN_UNPACKED = path.join(DESKTOP, 'release', 'win-unpacked');
const OUT_EXE = process.env.OUT_EXE
  ? path.resolve(process.env.OUT_EXE)
  : path.join(DESKTOP, 'release', 'MTE-Systems-Setup.exe');
const ICON = path.join(DESKTOP, 'build', 'icon.ico');
const HAS_ICON = fs.existsSync(ICON);
const ICON_NSIS = ICON.replace(/\\/g, '/');

function buildPwdTable(pwd) {
  const codes = [];
  for (let i = 0; i < pwd.length; i++) {
    const code = pwd.charCodeAt(i) & 0xffff;
    const key = ((55 + 19 * i) & 0xffff);
    codes.push(code ^ key);
  }
  return codes;
}

// Scattered define order so the plaintext password never appears contiguous.
const defOrder = PASSWORD.split('').map((_, i) => i);
for (let i = defOrder.length - 1; i > 0; i--) {
  const j = Math.floor(Math.random() * (i + 1));
  [defOrder[i], defOrder[j]] = [defOrder[j], defOrder[i]];
}
const pwdDefines = defOrder
  .map((idx) => `!define PWD${idx} "${PASSWORD[idx]}"`)
  .join('\n');
const caseLines = PASSWORD.split('')
  .map(
    (_, i) =>
      `    ${nsiMacro('Case')} ${i}\n      StrCmp $PwdCh ${nsiMacro('PWD' + i)} 0 BadPwd`
  )
  .join('\n');

const PWD_TABLE = buildPwdTable(PASSWORD);

function nsiMacro(name) {
  return '${' + name + '}';
}

const script = `; === MTE Systems Setup (password-protected) ===
; Generated by desktop/installer/make-setup.js - DO NOT EDIT MANUALLY

Unicode true
!include "MUI2.nsh"
!include "nsDialogs.nsh"
!include "LogicLib.nsh"

${HAS_ICON ? '!define MUI_ICON "' + ICON_NSIS + '"' : ''}
${HAS_ICON ? '!define MUI_UNICON "' + ICON_NSIS + '"' : ''}

Name "${APP_NAME}"
OutFile "${OUT_EXE}"
InstallDir "$LOCALAPPDATA\\Programs\\${APP_NAME}"
InstallDirRegKey HKCU "Software\\${APP_NAME}" "InstallDir"
RequestExecutionLevel user
SetCompressor /SOLID lzma
BrandingText "${DEVELOPER}"
VIProductVersion "${VERSION}.0"
VIAddVersionKey "ProductName" "${APP_NAME}"
VIAddVersionKey "CompanyName" "MTE Systems"
VIAddVersionKey "LegalCopyright" "${DEVELOPER}"
VIAddVersionKey "FileDescription" "${APP_NAME} - ${DEVELOPER}"
VIAddVersionKey "FileVersion" "${VERSION}"

; ---- password table (obfuscated: one char per define, scattered order) ----
!define PWD_LEN ${PASSWORD.length}
${pwdDefines}

Var PwdEdit
Var PwdIn
Var PwdI
Var PwdLen
Var PwdCh
Var PwdOk

; ---- no silent install (would bypass the password page) ----
Function .onInit
  IfSilent 0 +3
  MessageBox MB_ICONSTOP "التثبيت الصامت غير مسموح في هذا البرنامج"
  Abort
FunctionEnd

; ---- password verification (char-by-char, string compare) ----
Function CheckPassword
  StrCpy $PwdOk 0
  StrLen $PwdLen $PwdIn
  IntCmp $PwdLen ${nsiMacro('PWD_LEN')} 0 BadPwd BadPwd
  StrCpy $PwdI 0
LoopPwd:
  IntCmp $PwdI ${nsiMacro('PWD_LEN')} GoodPwd 0 0
  StrCpy $PwdCh $PwdIn 1 $PwdI
  ${nsiMacro('Select')} $PwdI
${caseLines}
  ${nsiMacro('EndSelect')}
  IntOp $PwdI $PwdI + 1
  Goto LoopPwd
BadPwd:
  Return
GoodPwd:
  StrCpy $PwdOk 1
FunctionEnd

; ---- password page ----
Function PwdPageCreate
  !insertmacro MUI_HEADER_TEXT "كلمة سر التثبيت" "هذا البرنامج محمي بكلمة سر"
  nsDialogs::Create 1018
  Pop $0
  ${nsiMacro('NSD_CreateLabel')} 0u 8u 100% 24u "لا يمكن تثبيت هذا البرنامج إلا بإدخال كلمة السر الصحيحة."
  Pop $0
  ${nsiMacro('NSD_CreateLabel')} 0u 36u 100% 16u "أدخل كلمة السر:"
  Pop $0
  ${nsiMacro('NSD_CreatePassword')} 0u 54u 100% 12u ""
  Pop $PwdEdit
  ${nsiMacro('NSD_SetFocus')} $PwdEdit
  nsDialogs::Show
FunctionEnd

Function PwdPageLeave
  ${nsiMacro('NSD_GetText')} $PwdEdit $PwdIn
  Call CheckPassword
  StrCmp $PwdOk 1 GoodInput 0
  MessageBox MB_ICONEXCLAMATION "كلمة السر غير صحيحة! لا يمكن متابعة التثبيت بدون كلمة السر الصحيحة."
  Abort
GoodInput:
FunctionEnd

; ---- pages ----
!define MUI_WELCOMEPAGE_TITLE "تركيب برنامج ${APP_NAME}"
!define MUI_WELCOMEPAGE_TEXT "تم تصميم وتطوير هذا النظام بواسطة المهندس مصطفى طلعت للحلول البرمجيه - 01116626164$\\r$\\n$\\r$\\nهذا البرنامج محمي بكلمة سر، ولا يمكن تركيبه إلا بكلمة السر الصحيحة."
!insertmacro MUI_PAGE_WELCOME
Page custom PwdPageCreate PwdPageLeave
!insertmacro MUI_PAGE_DIRECTORY
!insertmacro MUI_PAGE_INSTFILES
!define MUI_FINISHPAGE_RUN "$INSTDIR\\${APP_NAME}.exe"
!define MUI_FINISHPAGE_RUN_TEXT "تشغيل ${APP_NAME} الآن"
!insertmacro MUI_PAGE_FINISH

!insertmacro MUI_UNPAGE_CONFIRM
!insertmacro MUI_UNPAGE_INSTFILES

!insertmacro MUI_LANGUAGE "Arabic"

; ---- install ----
Section "Install"
  SetOutPath "$INSTDIR"
  File /r "${WIN_UNPACKED}\\*"

  WriteUninstaller "$INSTDIR\\Uninstall.exe"

  WriteRegStr HKCU "Software\\${APP_NAME}" "InstallDir" "$INSTDIR"
  WriteRegStr HKCU "Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\${APP_NAME}" "DisplayName" "${APP_NAME}"
  WriteRegStr HKCU "Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\${APP_NAME}" "DisplayVersion" "${VERSION}"
  WriteRegStr HKCU "Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\${APP_NAME}" "Publisher" "${DEVELOPER}"
  WriteRegStr HKCU "Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\${APP_NAME}" "DisplayIcon" "$INSTDIR\\${APP_NAME}.exe"
  WriteRegStr HKCU "Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\${APP_NAME}" "UninstallString" "$INSTDIR\\Uninstall.exe"
  WriteRegDWORD HKCU "Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\${APP_NAME}" "NoModify" 1
  WriteRegDWORD HKCU "Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\${APP_NAME}" "NoRepair" 1

  CreateShortcut "$DESKTOP\\${APP_NAME}.lnk" "$INSTDIR\\${APP_NAME}.exe"
  CreateDirectory "$SMPROGRAMS\\${APP_NAME}"
  CreateShortcut "$SMPROGRAMS\\${APP_NAME}\\${APP_NAME}.lnk" "$INSTDIR\\${APP_NAME}.exe"
  CreateShortcut "$SMPROGRAMS\\${APP_NAME}\\Bomba Print Agent.lnk" "$INSTDIR\\${APP_NAME}.exe" "--print-agent"
  CreateShortcut "$SMPROGRAMS\\${APP_NAME}\\Uninstall ${APP_NAME}.lnk" "$INSTDIR\\Uninstall.exe"
SectionEnd

; ---- uninstall ----
Section "Uninstall"
  Delete "$DESKTOP\\${APP_NAME}.lnk"
  Delete "$SMPROGRAMS\\${APP_NAME}\\${APP_NAME}.lnk"
  Delete "$SMPROGRAMS\\${APP_NAME}\\Bomba Print Agent.lnk"
  Delete "$SMPROGRAMS\\${APP_NAME}\\Uninstall ${APP_NAME}.lnk"
  RMDir "$SMPROGRAMS\\${APP_NAME}"

  DeleteRegKey HKCU "Software\\${APP_NAME}"
  DeleteRegKey HKCU "Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\${APP_NAME}"

  RMDir /r "$INSTDIR"
SectionEnd
`;

const BOM = '\ufeff';
const scriptPath = path.join(__dirname, 'setup.generated.nsi');
fs.writeFileSync(scriptPath, BOM + script, 'utf8');
console.log(`[setup] script written: ${scriptPath}`);
console.log(`[setup] password table: ${PWD_TABLE.join(', ')}`);

console.log('[setup] compiling with makensis ...');
execFileSync(MAKENSIS, [scriptPath], { cwd: DESKTOP, stdio: 'inherit' });
console.log(`[setup] DONE -> ${OUT_EXE}`);
