; === MTE Systems Setup (password-protected) ===
; Generated by desktop/installer/make-setup.js - DO NOT EDIT MANUALLY

Unicode true
!include "MUI2.nsh"
!include "nsDialogs.nsh"
!include "LogicLib.nsh"

!define MUI_ICON "H:/My Work/Naruto/New folder (2)/project/desktop/build/icon.ico"
!define MUI_UNICON "H:/My Work/Naruto/New folder (2)/project/desktop/build/icon.ico"

Name "MTE Systems"
OutFile "H:\My Work\Naruto\New folder (2)\project\desktop\MTE-Systems-Setup-71.exe"
InstallDir "$LOCALAPPDATA\Programs\MTE Systems"
InstallDirRegKey HKCU "Software\MTE Systems" "InstallDir"
RequestExecutionLevel user
SetCompressor /SOLID lzma
BrandingText "تم تصميم وتطوير هذا النظام بواسطة المهندس مصطفى طلعت للحلول البرمجيه - 01116626164"
VIProductVersion "1.0.0.0"
VIAddVersionKey "ProductName" "MTE Systems"
VIAddVersionKey "CompanyName" "MTE Systems"
VIAddVersionKey "LegalCopyright" "تم تصميم وتطوير هذا النظام بواسطة المهندس مصطفى طلعت للحلول البرمجيه - 01116626164"
VIAddVersionKey "FileDescription" "MTE Systems - تم تصميم وتطوير هذا النظام بواسطة المهندس مصطفى طلعت للحلول البرمجيه - 01116626164"
VIAddVersionKey "FileVersion" "1.0.0"

; ---- password table (obfuscated: one char per define, scattered order) ----
!define PWD_LEN 7
!define PWD2 "2"
!define PWD1 "3"
!define PWD5 "1"
!define PWD6 "9"
!define PWD0 "6"
!define PWD3 "4"
!define PWD4 "9"

Var PwdEdit
Var PwdIn
Var PwdI
Var PwdLen
Var PwdCh
Var PwdOk

; ---- no silent install (would bypass the password page) ----
Function .onInit
  IfSilent 0 +3
  MessageBox MB_ICONSTOP "التثبيت الصامت غير مسموح في هذا البرنامج"
  Abort
FunctionEnd

; ---- password verification (char-by-char, string compare) ----
Function CheckPassword
  StrCpy $PwdOk 0
  StrLen $PwdLen $PwdIn
  IntCmp $PwdLen ${PWD_LEN} 0 BadPwd BadPwd
  StrCpy $PwdI 0
LoopPwd:
  IntCmp $PwdI ${PWD_LEN} GoodPwd 0 0
  StrCpy $PwdCh $PwdIn 1 $PwdI
  ${Select} $PwdI
    ${Case} 0
      StrCmp $PwdCh ${PWD0} 0 BadPwd
    ${Case} 1
      StrCmp $PwdCh ${PWD1} 0 BadPwd
    ${Case} 2
      StrCmp $PwdCh ${PWD2} 0 BadPwd
    ${Case} 3
      StrCmp $PwdCh ${PWD3} 0 BadPwd
    ${Case} 4
      StrCmp $PwdCh ${PWD4} 0 BadPwd
    ${Case} 5
      StrCmp $PwdCh ${PWD5} 0 BadPwd
    ${Case} 6
      StrCmp $PwdCh ${PWD6} 0 BadPwd
  ${EndSelect}
  IntOp $PwdI $PwdI + 1
  Goto LoopPwd
BadPwd:
  Return
GoodPwd:
  StrCpy $PwdOk 1
FunctionEnd

; ---- password page ----
Function PwdPageCreate
  !insertmacro MUI_HEADER_TEXT "كلمة سر التثبيت" "هذا البرنامج محمي بكلمة سر"
  nsDialogs::Create 1018
  Pop $0
  ${NSD_CreateLabel} 0u 8u 100% 24u "لا يمكن تثبيت هذا البرنامج إلا بإدخال كلمة السر الصحيحة."
  Pop $0
  ${NSD_CreateLabel} 0u 36u 100% 16u "أدخل كلمة السر:"
  Pop $0
  ${NSD_CreatePassword} 0u 54u 100% 12u ""
  Pop $PwdEdit
  ${NSD_SetFocus} $PwdEdit
  nsDialogs::Show
FunctionEnd

Function PwdPageLeave
  ${NSD_GetText} $PwdEdit $PwdIn
  Call CheckPassword
  StrCmp $PwdOk 1 GoodInput 0
  MessageBox MB_ICONEXCLAMATION "كلمة السر غير صحيحة! لا يمكن متابعة التثبيت بدون كلمة السر الصحيحة."
  Abort
GoodInput:
FunctionEnd

; ---- pages ----
!define MUI_WELCOMEPAGE_TITLE "تركيب برنامج MTE Systems"
!define MUI_WELCOMEPAGE_TEXT "تم تصميم وتطوير هذا النظام بواسطة المهندس مصطفى طلعت للحلول البرمجيه - 01116626164$\r$\n$\r$\nهذا البرنامج محمي بكلمة سر، ولا يمكن تركيبه إلا بكلمة السر الصحيحة."
!insertmacro MUI_PAGE_WELCOME
Page custom PwdPageCreate PwdPageLeave
!insertmacro MUI_PAGE_DIRECTORY
!insertmacro MUI_PAGE_INSTFILES
!define MUI_FINISHPAGE_RUN "$INSTDIR\MTE Systems.exe"
!define MUI_FINISHPAGE_RUN_TEXT "تشغيل MTE Systems الآن"
!insertmacro MUI_PAGE_FINISH

!insertmacro MUI_UNPAGE_CONFIRM
!insertmacro MUI_UNPAGE_INSTFILES

!insertmacro MUI_LANGUAGE "Arabic"

; ---- install ----
Section "Install"
  SetOutPath "$INSTDIR"
  File /r "H:\My Work\Naruto\New folder (2)\project\desktop\release\win-unpacked\*"

  WriteUninstaller "$INSTDIR\Uninstall.exe"

  WriteRegStr HKCU "Software\MTE Systems" "InstallDir" "$INSTDIR"
  WriteRegStr HKCU "Software\Microsoft\Windows\CurrentVersion\Uninstall\MTE Systems" "DisplayName" "MTE Systems"
  WriteRegStr HKCU "Software\Microsoft\Windows\CurrentVersion\Uninstall\MTE Systems" "DisplayVersion" "1.0.0"
  WriteRegStr HKCU "Software\Microsoft\Windows\CurrentVersion\Uninstall\MTE Systems" "Publisher" "تم تصميم وتطوير هذا النظام بواسطة المهندس مصطفى طلعت للحلول البرمجيه - 01116626164"
  WriteRegStr HKCU "Software\Microsoft\Windows\CurrentVersion\Uninstall\MTE Systems" "DisplayIcon" "$INSTDIR\MTE Systems.exe"
  WriteRegStr HKCU "Software\Microsoft\Windows\CurrentVersion\Uninstall\MTE Systems" "UninstallString" "$INSTDIR\Uninstall.exe"
  WriteRegDWORD HKCU "Software\Microsoft\Windows\CurrentVersion\Uninstall\MTE Systems" "NoModify" 1
  WriteRegDWORD HKCU "Software\Microsoft\Windows\CurrentVersion\Uninstall\MTE Systems" "NoRepair" 1

  CreateShortcut "$DESKTOP\MTE Systems.lnk" "$INSTDIR\MTE Systems.exe"
  CreateDirectory "$SMPROGRAMS\MTE Systems"
  CreateShortcut "$SMPROGRAMS\MTE Systems\MTE Systems.lnk" "$INSTDIR\MTE Systems.exe"
  CreateShortcut "$SMPROGRAMS\MTE Systems\Bomba Print Agent.lnk" "$INSTDIR\MTE Systems.exe" "--print-agent"
  CreateDirectory "$APPDATA\Microsoft\Windows\Start Menu\Programs\Startup"
  CreateShortcut "$APPDATA\Microsoft\Windows\Start Menu\Programs\Startup\Bomba Print Agent.lnk" "$INSTDIR\MTE Systems.exe" "--print-agent"
  CreateShortcut "$SMPROGRAMS\MTE Systems\Uninstall MTE Systems.lnk" "$INSTDIR\Uninstall.exe"
SectionEnd

; ---- uninstall ----
Section "Uninstall"
  Delete "$DESKTOP\MTE Systems.lnk"
  Delete "$SMPROGRAMS\MTE Systems\MTE Systems.lnk"
  Delete "$SMPROGRAMS\MTE Systems\Bomba Print Agent.lnk"
  Delete "$APPDATA\Microsoft\Windows\Start Menu\Programs\Startup\Bomba Print Agent.lnk"
  Delete "$SMPROGRAMS\MTE Systems\Uninstall MTE Systems.lnk"
  RMDir "$SMPROGRAMS\MTE Systems"

  DeleteRegKey HKCU "Software\MTE Systems"
  DeleteRegKey HKCU "Software\Microsoft\Windows\CurrentVersion\Uninstall\MTE Systems"

  RMDir /r "$INSTDIR"
SectionEnd
