/**
 * Currency names in multiple languages
 * Shared between frontend and backend
 * 
 * This provides human-readable names for all currencies
 */

export const CURRENCY_NAMES = {
    // Africa
    'DZD': { ar: 'دينار جزائري', en: 'Algerian Dinar', fr: 'Dinar algérien' },
    'AOA': { ar: 'كوانزا أنغولي', en: 'Angolan Kwanza', fr: 'Kwanza angolais' },
    'BWP': { ar: 'بولا بوتسواني', en: 'Botswana Pula', fr: 'Pula botswanais' },
    'BIF': { ar: 'فرنك بوروندي', en: 'Burundian Franc', fr: 'Franc burundais' },
    'XAF': { ar: 'فرنك وسط أفريقي', en: 'Central African CFA Franc', fr: 'Franc CFA (BEAC)' },
    'XOF': { ar: 'فرنك غرب أفريقي', en: 'West African CFA Franc', fr: 'Franc CFA (BCEAO)' },
    'KMF': { ar: 'فرنك قمري', en: 'Comorian Franc', fr: 'Franc comorien' },
    'CDF': { ar: 'فرنك كونغولي', en: 'Congolese Franc', fr: 'Franc congolais' },
    'DJF': { ar: 'فرنك جيبوتي', en: 'Djiboutian Franc', fr: 'Franc djiboutien' },
    'EGP': { ar: 'جنيه مصري', en: 'Egyptian Pound', fr: 'Livre égyptienne' },
    'ERN': { ar: 'ناكفا إريتري', en: 'Eritrean Nakfa', fr: 'Nakfa érythréen' },
    'ETB': { ar: 'بير إثيوبي', en: 'Ethiopian Birr', fr: 'Birr éthiopien' },
    'GMD': { ar: 'دالاسي غامبي', en: 'Gambian Dalasi', fr: 'Dalasi gambien' },
    'GHS': { ar: 'سيدي غاني', en: 'Ghanaian Cedi', fr: 'Cedi ghanéen' },
    'GNF': { ar: 'فرنك غيني', en: 'Guinean Franc', fr: 'Franc guinéen' },
    'KES': { ar: 'شلن كيني', en: 'Kenyan Shilling', fr: 'Shilling kényan' },
    'LSL': { ar: 'لوتي ليسوتو', en: 'Lesotho Loti', fr: 'Loti lesothan' },
    'LRD': { ar: 'دولار ليبيري', en: 'Liberian Dollar', fr: 'Dollar libérien' },
    'LYD': { ar: 'دينار ليبي', en: 'Libyan Dinar', fr: 'Dinar libyen' },
    'MGA': { ar: 'أرياري مدغشقري', en: 'Malagasy Ariary', fr: 'Ariary malgache' },
    'MWK': { ar: 'كواشا ملاوي', en: 'Malawian Kwacha', fr: 'Kwacha malawite' },
    'MUR': { ar: 'روبية موريشيوسية', en: 'Mauritian Rupee', fr: 'Roupie mauricienne' },
    'MAD': { ar: 'درهم مغربي', en: 'Moroccan Dirham', fr: 'Dirham marocain' },
    'MZN': { ar: 'متيكال موزمبيقي', en: 'Mozambican Metical', fr: 'Metical mozambicain' },
    'NAD': { ar: 'دولار ناميبي', en: 'Namibian Dollar', fr: 'Dollar namibien' },
    'NGN': { ar: 'نايرا نيجيري', en: 'Nigerian Naira', fr: 'Naira nigérian' },
    'RWF': { ar: 'فرنك رواندي', en: 'Rwandan Franc', fr: 'Franc rwandais' },
    'STN': { ar: 'دوبرا ساو تومي', en: 'São Tomé Dobra', fr: 'Dobra santoméen' },
    'SCR': { ar: 'روبية سيشلية', en: 'Seychellois Rupee', fr: 'Roupie seychelloise' },
    'SLL': { ar: 'ليون سيراليوني', en: 'Sierra Leonean Leone', fr: 'Leone sierra-léonais' },
    'SOS': { ar: 'شلن صومالي', en: 'Somali Shilling', fr: 'Shilling somalien' },
    'ZAR': { ar: 'راند جنوب أفريقي', en: 'South African Rand', fr: 'Rand sud-africain' },
    'SSP': { ar: 'جنيه جنوب سوداني', en: 'South Sudanese Pound', fr: 'Livre sud-soudanaise' },
    'SDG': { ar: 'جنيه سوداني', en: 'Sudanese Pound', fr: 'Livre soudanaise' },
    'SZL': { ar: 'ليلانغيني سوازيلندي', en: 'Swazi Lilangeni', fr: 'Lilangeni swazi' },
    'TZS': { ar: 'شلن تنزاني', en: 'Tanzanian Shilling', fr: 'Shilling tanzanien' },
    'TND': { ar: 'دينار تونسي', en: 'Tunisian Dinar', fr: 'Dinar tunisien' },
    'UGX': { ar: 'شلن أوغندي', en: 'Ugandan Shilling', fr: 'Shilling ougandais' },
    'ZMW': { ar: 'كواشا زامبي', en: 'Zambian Kwacha', fr: 'Kwacha zambien' },
    'ZWL': { ar: 'دولار زيمبابوي', en: 'Zimbabwean Dollar', fr: 'Dollar zimbabwéen' },
    'MRU': { ar: 'أوقية موريتانية', en: 'Mauritanian Ouguiya', fr: 'Ouguiya mauritanien' },

    // Americas
    'ARS': { ar: 'بيزو أرجنتيني', en: 'Argentine Peso', fr: 'Peso argentin' },
    'AWG': { ar: 'فلورين أروبي', en: 'Aruban Florin', fr: 'Florin arubais' },
    'BSD': { ar: 'دولار باهامي', en: 'Bahamian Dollar', fr: 'Dollar bahaméen' },
    'BBD': { ar: 'دولار بربادوسي', en: 'Barbadian Dollar', fr: 'Dollar barbadien' },
    'BZD': { ar: 'دولار بليزي', en: 'Belize Dollar', fr: 'Dollar bélizien' },
    'BMD': { ar: 'دولار برمودي', en: 'Bermudian Dollar', fr: 'Dollar bermudien' },
    'BOB': { ar: 'بوليفيانو بوليفي', en: 'Bolivian Boliviano', fr: 'Boliviano bolivien' },
    'BRL': { ar: 'ريال برازيلي', en: 'Brazilian Real', fr: 'Réal brésilien' },
    'CAD': { ar: 'دولار كندي', en: 'Canadian Dollar', fr: 'Dollar canadien' },
    'KYD': { ar: 'دولار جزر كايمان', en: 'Cayman Islands Dollar', fr: 'Dollar des îles Caïmans' },
    'CLP': { ar: 'بيزو تشيلي', en: 'Chilean Peso', fr: 'Peso chilien' },
    'COP': { ar: 'بيزو كولومبي', en: 'Colombian Peso', fr: 'Peso colombien' },
    'CRC': { ar: 'كولون كوستاريكي', en: 'Costa Rican Colón', fr: 'Colón costaricain' },
    'CUP': { ar: 'بيزو كوبي', en: 'Cuban Peso', fr: 'Peso cubain' },
    'DOP': { ar: 'بيزو دومينيكاني', en: 'Dominican Peso', fr: 'Peso dominicain' },
    'XCD': { ar: 'دولار شرق الكاريبي', en: 'East Caribbean Dollar', fr: 'Dollar des Caraïbes orientales' },
    'SVC': { ar: 'كولون سلفادوري', en: 'Salvadoran Colón', fr: 'Colón salvadorien' },
    'FKP': { ar: 'جنيه جزر فوكلاند', en: 'Falkland Islands Pound', fr: 'Livre des Malouines' },
    'GTQ': { ar: 'كتزال غواتيمالي', en: 'Guatemalan Quetzal', fr: 'Quetzal guatémaltèque' },
    'GYD': { ar: 'دولار غياني', en: 'Guyanese Dollar', fr: 'Dollar guyanien' },
    'HTG': { ar: 'غورد هايتي', en: 'Haitian Gourde', fr: 'Gourde haïtienne' },
    'HNL': { ar: 'ليمبيرا هندوراسي', en: 'Honduran Lempira', fr: 'Lempira hondurien' },
    'JMD': { ar: 'دولار جامايكي', en: 'Jamaican Dollar', fr: 'Dollar jamaïcain' },
    'MXN': { ar: 'بيزو مكسيكي', en: 'Mexican Peso', fr: 'Peso mexicain' },
    'NIO': { ar: 'كوردوبا نيكاراغوي', en: 'Nicaraguan Córdoba', fr: 'Córdoba nicaraguayen' },
    'PAB': { ar: 'بالبوا بنمي', en: 'Panamanian Balboa', fr: 'Balboa panaméen' },
    'PYG': { ar: 'غواراني باراغواي', en: 'Paraguayan Guaraní', fr: 'Guaraní paraguayen' },
    'PEN': { ar: 'سول بيروفي', en: 'Peruvian Sol', fr: 'Sol péruvien' },
    'SRD': { ar: 'دولار سورينامي', en: 'Surinamese Dollar', fr: 'Dollar surinamais' },
    'TTD': { ar: 'دولار ترينيداد وتوباغو', en: 'Trinidad and Tobago Dollar', fr: 'Dollar de Trinité-et-Tobago' },
    'USD': { ar: 'دولار أمريكي', en: 'US Dollar', fr: 'Dollar américain' },
    'UYU': { ar: 'بيزو أوروغواي', en: 'Uruguayan Peso', fr: 'Peso uruguayen' },
    'VES': { ar: 'بوليفار فنزويلي', en: 'Venezuelan Bolívar', fr: 'Bolívar vénézuélien' },

    // Asia
    'AFN': { ar: 'أفغاني أفغانستاني', en: 'Afghan Afghani', fr: 'Afghani afghan' },
    'AMD': { ar: 'درام أرميني', en: 'Armenian Dram', fr: 'Dram arménien' },
    'AZN': { ar: 'مانات أذربيجاني', en: 'Azerbaijani Manat', fr: 'Manat azéri' },
    'BHD': { ar: 'دينار بحريني', en: 'Bahraini Dinar', fr: 'Dinar bahreïni' },
    'BDT': { ar: 'تاكا بنغلاديشي', en: 'Bangladeshi Taka', fr: 'Taka bangladais' },
    'BTN': { ar: 'نغولترم بوتاني', en: 'Bhutanese Ngultrum', fr: 'Ngultrum bhoutanais' },
    'BND': { ar: 'دولار بروناي', en: 'Brunei Dollar', fr: 'Dollar de Brunei' },
    'KHR': { ar: 'ريال كمبودي', en: 'Cambodian Riel', fr: 'Riel cambodgien' },
    'CNY': { ar: 'يوان صيني', en: 'Chinese Yuan', fr: 'Yuan chinois' },
    'GEL': { ar: 'لاري جورجي', en: 'Georgian Lari', fr: 'Lari géorgien' },
    'HKD': { ar: 'دولار هونغ كونغ', en: 'Hong Kong Dollar', fr: 'Dollar de Hong Kong' },
    'INR': { ar: 'روبية هندية', en: 'Indian Rupee', fr: 'Roupie indienne' },
    'IDR': { ar: 'روبية إندونيسية', en: 'Indonesian Rupiah', fr: 'Roupie indonésienne' },
    'IRR': { ar: 'ريال إيراني', en: 'Iranian Rial', fr: 'Rial iranien' },
    'IQD': { ar: 'دينار عراقي', en: 'Iraqi Dinar', fr: 'Dinar irakien' },
    'ILS': { ar: 'شيكل', en: 'Shekel', fr: 'Shekel' },
    'JPY': { ar: 'ين ياباني', en: 'Japanese Yen', fr: 'Yen japonais' },
    'JOD': { ar: 'دينار أردني', en: 'Jordanian Dinar', fr: 'Dinar jordanien' },
    'KZT': { ar: 'تنغي كازاخستاني', en: 'Kazakhstani Tenge', fr: 'Tenge kazakh' },
    'KWD': { ar: 'دينار كويتي', en: 'Kuwaiti Dinar', fr: 'Dinar koweïtien' },
    'KGS': { ar: 'سوم قيرغيزستاني', en: 'Kyrgyzstani Som', fr: 'Som kirghize' },
    'LAK': { ar: 'كيب لاوسي', en: 'Lao Kip', fr: 'Kip laotien' },
    'LBP': { ar: 'ليرة لبنانية', en: 'Lebanese Pound', fr: 'Livre libanaise' },
    'MOP': { ar: 'باتاكا ماكاوي', en: 'Macanese Pataca', fr: 'Pataca macanaise' },
    'MYR': { ar: 'رينغيت ماليزي', en: 'Malaysian Ringgit', fr: 'Ringgit malaisien' },
    'MVR': { ar: 'روفيه مالديفي', en: 'Maldivian Rufiyaa', fr: 'Rufiyaa maldivienne' },
    'MNT': { ar: 'توغروغ منغولي', en: 'Mongolian Tögrög', fr: 'Tugrik mongol' },
    'MMK': { ar: 'كيات ميانماري', en: 'Myanmar Kyat', fr: 'Kyat birman' },
    'NPR': { ar: 'روبية نيبالية', en: 'Nepalese Rupee', fr: 'Roupie népalaise' },
    'KPW': { ar: 'وون كوري شمالي', en: 'North Korean Won', fr: 'Won nord-coréen' },
    'OMR': { ar: 'ريال عماني', en: 'Omani Rial', fr: 'Rial omanais' },
    'PKR': { ar: 'روبية باكستانية', en: 'Pakistani Rupee', fr: 'Roupie pakistanaise' },
    'PHP': { ar: 'بيزو فلبيني', en: 'Philippine Peso', fr: 'Peso philippin' },
    'QAR': { ar: 'ريال قطري', en: 'Qatari Riyal', fr: 'Riyal qatarien' },
    'SAR': { ar: 'ريال سعودي', en: 'Saudi Riyal', fr: 'Riyal saoudien' },
    'SGD': { ar: 'دولار سنغافوري', en: 'Singapore Dollar', fr: 'Dollar de Singapour' },
    'KRW': { ar: 'وون كوري جنوبي', en: 'South Korean Won', fr: 'Won sud-coréen' },
    'LKR': { ar: 'روبية سريلانكية', en: 'Sri Lankan Rupee', fr: 'Roupie srilankaise' },
    'SYP': { ar: 'ليرة سورية', en: 'Syrian Pound', fr: 'Livre syrienne' },
    'TWD': { ar: 'دولار تايواني', en: 'New Taiwan Dollar', fr: 'Dollar taïwanais' },
    'TJS': { ar: 'سوموني طاجيكستاني', en: 'Tajikistani Somoni', fr: 'Somoni tadjik' },
    'THB': { ar: 'بات تايلندي', en: 'Thai Baht', fr: 'Baht thaïlandais' },
    'TMT': { ar: 'مانات تركمانستاني', en: 'Turkmenistan Manat', fr: 'Manat turkmène' },
    'AED': { ar: 'درهم إماراتي', en: 'UAE Dirham', fr: 'Dirham des EAU' },
    'UZS': { ar: 'سوم أوزبكستاني', en: 'Uzbekistani Som', fr: 'Sum ouzbek' },
    'VND': { ar: 'دونغ فيتنامي', en: 'Vietnamese Đồng', fr: 'Dong vietnamien' },
    'YER': { ar: 'ريال يمني', en: 'Yemeni Rial', fr: 'Rial yéménite' },

    // Europe
    'ALL': { ar: 'ليك ألباني', en: 'Albanian Lek', fr: 'Lek albanais' },
    'EUR': { ar: 'يورو', en: 'Euro', fr: 'Euro' },
    'BAM': { ar: 'مارك بوسني', en: 'Bosnia-Herzegovina Mark', fr: 'Mark convertible' },
    'BGN': { ar: 'ليف بلغاري', en: 'Bulgarian Lev', fr: 'Lev bulgare' },
    'HRK': { ar: 'كونا كرواتي', en: 'Croatian Kuna', fr: 'Kuna croate' },
    'CZK': { ar: 'كورونا تشيكية', en: 'Czech Koruna', fr: 'Couronne tchèque' },
    'DKK': { ar: 'كرونة دنماركية', en: 'Danish Krone', fr: 'Couronne danoise' },
    'GBP': { ar: 'جنيه إسترليني', en: 'British Pound', fr: 'Livre sterling' },
    'HUF': { ar: 'فورنت مجري', en: 'Hungarian Forint', fr: 'Forint hongrois' },
    'ISK': { ar: 'كرونة آيسلندية', en: 'Icelandic Króna', fr: 'Couronne islandaise' },
    'CHF': { ar: 'فرنك سويسري', en: 'Swiss Franc', fr: 'Franc suisse' },
    'MDL': { ar: 'ليو مولدوفي', en: 'Moldovan Leu', fr: 'Leu moldave' },
    'MKD': { ar: 'دينار مقدوني', en: 'Macedonian Denar', fr: 'Denar macédonien' },
    'NOK': { ar: 'كرونة نرويجية', en: 'Norwegian Krone', fr: 'Couronne norvégienne' },
    'PLN': { ar: 'زلوتي بولندي', en: 'Polish Złoty', fr: 'Złoty polonais' },
    'RON': { ar: 'ليو روماني', en: 'Romanian Leu', fr: 'Leu roumain' },
    'RUB': { ar: 'روبل روسي', en: 'Russian Ruble', fr: 'Rouble russe' },
    'RSD': { ar: 'دينار صربي', en: 'Serbian Dinar', fr: 'Dinar serbe' },
    'SEK': { ar: 'كرونة سويدية', en: 'Swedish Krona', fr: 'Couronne suédoise' },
    'TRY': { ar: 'ليرة تركية', en: 'Turkish Lira', fr: 'Livre turque' },
    'UAH': { ar: 'هريفنيا أوكرانية', en: 'Ukrainian Hryvnia', fr: 'Hryvnia ukrainienne' },
    'GIP': { ar: 'جنيه جبل طارق', en: 'Gibraltar Pound', fr: 'Livre de Gibraltar' },
    'BYN': { ar: 'روبل بيلاروسي', en: 'Belarusian Ruble', fr: 'Rouble biélorusse' },

    // Oceania
    'AUD': { ar: 'دولار أسترالي', en: 'Australian Dollar', fr: 'Dollar australien' },
    'FJD': { ar: 'دولار فيجي', en: 'Fijian Dollar', fr: 'Dollar fidjien' },
    'NZD': { ar: 'دولار نيوزيلندي', en: 'New Zealand Dollar', fr: 'Dollar néo-zélandais' },
    'PGK': { ar: 'كينا بابوا غينيا الجديدة', en: 'Papua New Guinean Kina', fr: 'Kina papouan' },
    'WST': { ar: 'تالا ساموي', en: 'Samoan Tālā', fr: 'Tala samoan' },
    'SBD': { ar: 'دولار جزر سليمان', en: 'Solomon Islands Dollar', fr: 'Dollar des îles Salomon' },
    'TOP': { ar: 'بانغا تونغي', en: 'Tongan Paʻanga', fr: 'Paʻanga tongien' },
    'VUV': { ar: 'فاتو فانواتي', en: 'Vanuatu Vatu', fr: 'Vatu vanuatuan' },
    'XPF': { ar: 'فرنك باسيفيكي', en: 'CFP Franc', fr: 'Franc CFP' },

    // Cryptocurrencies
    'BTC': { ar: 'بيتكوين', en: 'Bitcoin', fr: 'Bitcoin' },
    'ETH': { ar: 'إيثريوم', en: 'Ethereum', fr: 'Ethereum' }
};

/**
 * Get currency name in specified language
 * @param {string} currencyCode - Currency code (EGP, SAR, etc.)
 * @param {string} language - Language code (ar, en, fr)
 * @returns {string} Currency name
 */
export const getCurrencyName = (currencyCode, language = 'ar') => {
    return CURRENCY_NAMES[currencyCode]?.[language] || currencyCode;
};
