/**
 * All world languages (ISO 639-1 codes)
 * Shared between frontend and backend
 * 
 * This is the single source of truth for supported languages
 */

export const WORLD_LANGUAGES = [
    { code: 'ar', name: 'العربية', nativeName: 'العربية', rtl: true },
    { code: 'en', name: 'English', nativeName: 'English', rtl: false },
    { code: 'fr', name: 'French', nativeName: 'Français', rtl: false },
    { code: 'es', name: 'Spanish', nativeName: 'Español', rtl: false },
    { code: 'de', name: 'German', nativeName: 'Deutsch', rtl: false },
    { code: 'it', name: 'Italian', nativeName: 'Italiano', rtl: false },
    { code: 'pt', name: 'Portuguese', nativeName: 'Português', rtl: false },
    { code: 'ru', name: 'Russian', nativeName: 'Русский', rtl: false },
    { code: 'zh', name: 'Chinese', nativeName: '中文', rtl: false },
    { code: 'ja', name: 'Japanese', nativeName: '日本語', rtl: false },
    { code: 'ko', name: 'Korean', nativeName: '한국어', rtl: false },
    { code: 'hi', name: 'Hindi', nativeName: 'हिन्दी', rtl: false },
    { code: 'bn', name: 'Bengali', nativeName: 'বাংলা', rtl: false },
    { code: 'pa', name: 'Punjabi', nativeName: 'ਪੰਜਾਬੀ', rtl: false },
    { code: 'te', name: 'Telugu', nativeName: 'తెలుగు', rtl: false },
    { code: 'mr', name: 'Marathi', nativeName: 'मराठी', rtl: false },
    { code: 'ta', name: 'Tamil', nativeName: 'தமிழ்', rtl: false },
    { code: 'ur', name: 'Urdu', nativeName: 'اردو', rtl: true },
    { code: 'tr', name: 'Turkish', nativeName: 'Türkçe', rtl: false },
    { code: 'vi', name: 'Vietnamese', nativeName: 'Tiếng Việt', rtl: false },
    { code: 'th', name: 'Thai', nativeName: 'ไทย', rtl: false },
    { code: 'pl', name: 'Polish', nativeName: 'Polski', rtl: false },
    { code: 'nl', name: 'Dutch', nativeName: 'Nederlands', rtl: false },
    { code: 'el', name: 'Greek', nativeName: 'Ελληνικά', rtl: false },
    { code: 'cs', name: 'Czech', nativeName: 'Čeština', rtl: false },
    { code: 'sv', name: 'Swedish', nativeName: 'Svenska', rtl: false },
    { code: 'ro', name: 'Romanian', nativeName: 'Română', rtl: false },
    { code: 'hu', name: 'Hungarian', nativeName: 'Magyar', rtl: false },
    { code: 'da', name: 'Danish', nativeName: 'Dansk', rtl: false },
    { code: 'fi', name: 'Finnish', nativeName: 'Suomi', rtl: false },
    { code: 'no', name: 'Norwegian', nativeName: 'Norsk', rtl: false },
    { code: 'sk', name: 'Slovak', nativeName: 'Slovenčina', rtl: false },
    { code: 'bg', name: 'Bulgarian', nativeName: 'Български', rtl: false },
    { code: 'hr', name: 'Croatian', nativeName: 'Hrvatski', rtl: false },
    { code: 'sr', name: 'Serbian', nativeName: 'Српски', rtl: false },
    { code: 'uk', name: 'Ukrainian', nativeName: 'Українська', rtl: false },
    { code: 'he', name: 'Hebrew', nativeName: 'עברית', rtl: true },
    { code: 'id', name: 'Indonesian', nativeName: 'Bahasa Indonesia', rtl: false },
    { code: 'ms', name: 'Malay', nativeName: 'Bahasa Melayu', rtl: false },
    { code: 'fa', name: 'Persian', nativeName: 'فارسی', rtl: true },
    { code: 'sw', name: 'Swahili', nativeName: 'Kiswahili', rtl: false },
    { code: 'af', name: 'Afrikaans', nativeName: 'Afrikaans', rtl: false },
    { code: 'sq', name: 'Albanian', nativeName: 'Shqip', rtl: false },
    { code: 'am', name: 'Amharic', nativeName: 'አማርኛ', rtl: false },
    { code: 'hy', name: 'Armenian', nativeName: 'Հայերեն', rtl: false },
    { code: 'az', name: 'Azerbaijani', nativeName: 'Azərbaycan', rtl: false },
    { code: 'eu', name: 'Basque', nativeName: 'Euskara', rtl: false },
    { code: 'be', name: 'Belarusian', nativeName: 'Беларуская', rtl: false },
    { code: 'bs', name: 'Bosnian', nativeName: 'Bosanski', rtl: false },
    { code: 'ca', name: 'Catalan', nativeName: 'Català', rtl: false },
    { code: 'et', name: 'Estonian', nativeName: 'Eesti', rtl: false },
    { code: 'tl', name: 'Filipino', nativeName: 'Filipino', rtl: false },
    { code: 'gl', name: 'Galician', nativeName: 'Galego', rtl: false },
    { code: 'ka', name: 'Georgian', nativeName: 'ქართული', rtl: false },
    { code: 'gu', name: 'Gujarati', nativeName: 'ગુજરાતી', rtl: false },
    { code: 'ha', name: 'Hausa', nativeName: 'Hausa', rtl: false },
    { code: 'is', name: 'Icelandic', nativeName: 'Íslenska', rtl: false },
    { code: 'ig', name: 'Igbo', nativeName: 'Igbo', rtl: false },
    { code: 'ga', name: 'Irish', nativeName: 'Gaeilge', rtl: false },
    { code: 'kn', name: 'Kannada', nativeName: 'ಕನ್ನಡ', rtl: false },
    { code: 'kk', name: 'Kazakh', nativeName: 'Қазақ', rtl: false },
    { code: 'km', name: 'Khmer', nativeName: 'ខ្មែរ', rtl: false },
    { code: 'ku', name: 'Kurdish', nativeName: 'Kurdî', rtl: false },
    { code: 'ky', name: 'Kyrgyz', nativeName: 'Кыргызча', rtl: false },
    { code: 'lo', name: 'Lao', nativeName: 'ລາວ', rtl: false },
    { code: 'lv', name: 'Latvian', nativeName: 'Latviešu', rtl: false },
    { code: 'lt', name: 'Lithuanian', nativeName: 'Lietuvių', rtl: false },
    { code: 'mk', name: 'Macedonian', nativeName: 'Македонски', rtl: false },
    { code: 'mg', name: 'Malagasy', nativeName: 'Malagasy', rtl: false },
    { code: 'ml', name: 'Malayalam', nativeName: 'മലയാളം', rtl: false },
    { code: 'mt', name: 'Maltese', nativeName: 'Malti', rtl: false },
    { code: 'mi', name: 'Maori', nativeName: 'Māori', rtl: false },
    { code: 'mn', name: 'Mongolian', nativeName: 'Монгол', rtl: false },
    { code: 'my', name: 'Myanmar', nativeName: 'မြန်မာ', rtl: false },
    { code: 'ne', name: 'Nepali', nativeName: 'नेपाली', rtl: false },
    { code: 'ps', name: 'Pashto', nativeName: 'پښتو', rtl: true },
    { code: 'si', name: 'Sinhala', nativeName: 'සිංහල', rtl: false },
    { code: 'sl', name: 'Slovenian', nativeName: 'Slovenščina', rtl: false },
    { code: 'so', name: 'Somali', nativeName: 'Soomaali', rtl: false },
    { code: 'su', name: 'Sundanese', nativeName: 'Basa Sunda', rtl: false },
    { code: 'tg', name: 'Tajik', nativeName: 'Тоҷикӣ', rtl: false },
    { code: 'tk', name: 'Turkmen', nativeName: 'Türkmen', rtl: false },
    { code: 'uz', name: 'Uzbek', nativeName: 'Oʻzbek', rtl: false },
    { code: 'cy', name: 'Welsh', nativeName: 'Cymraeg', rtl: false },
    { code: 'xh', name: 'Xhosa', nativeName: 'isiXhosa', rtl: false },
    { code: 'yi', name: 'Yiddish', nativeName: 'ייִדיש', rtl: true },
    { code: 'yo', name: 'Yoruba', nativeName: 'Yorùbá', rtl: false },
    { code: 'zu', name: 'Zulu', nativeName: 'isiZulu', rtl: false },
    { code: 'jv', name: 'Javanese', nativeName: 'Basa Jawa', rtl: false },
    { code: 'ceb', name: 'Cebuano', nativeName: 'Cebuano', rtl: false },
    { code: 'ht', name: 'Haitian Creole', nativeName: 'Kreyòl Ayisyen', rtl: false },
    { code: 'la', name: 'Latin', nativeName: 'Latina', rtl: false },
    { code: 'lb', name: 'Luxembourgish', nativeName: 'Lëtzebuergesch', rtl: false },
    { code: 'ny', name: 'Chichewa', nativeName: 'Chichewa', rtl: false },
    { code: 'sn', name: 'Shona', nativeName: 'chiShona', rtl: false },
    { code: 'st', name: 'Sesotho', nativeName: 'Sesotho', rtl: false },
    { code: 'sd', name: 'Sindhi', nativeName: 'سنڌي', rtl: true },
    { code: 'gd', name: 'Scottish Gaelic', nativeName: 'Gàidhlig', rtl: false },
    { code: 'fy', name: 'Frisian', nativeName: 'Frysk', rtl: false },
    { code: 'co', name: 'Corsican', nativeName: 'Corsu', rtl: false },
    { code: 'eo', name: 'Esperanto', nativeName: 'Esperanto', rtl: false },
    { code: 'haw', name: 'Hawaiian', nativeName: 'ʻŌlelo Hawaiʻi', rtl: false },
    { code: 'iu', name: 'Inuktitut', nativeName: 'ᐃᓄᒃᑎᑐᑦ', rtl: false },
    { code: 'kl', name: 'Greenlandic', nativeName: 'Kalaallisut', rtl: false },
    { code: 'rw', name: 'Kinyarwanda', nativeName: 'Ikinyarwanda', rtl: false },
    { code: 'lg', name: 'Luganda', nativeName: 'Luganda', rtl: false },
    { code: 'ln', name: 'Lingala', nativeName: 'Lingála', rtl: false },
    { code: 'lu', name: 'Luba-Katanga', nativeName: 'Kiluba', rtl: false },
    { code: 'or', name: 'Odia', nativeName: 'ଓଡ଼ିଆ', rtl: false },
    { code: 'om', name: 'Oromo', nativeName: 'Oromoo', rtl: false },
    { code: 'qu', name: 'Quechua', nativeName: 'Runa Simi', rtl: false },
    { code: 'sm', name: 'Samoan', nativeName: 'Gagana Samoa', rtl: false },
    { code: 'sa', name: 'Sanskrit', nativeName: 'संस्कृतम्', rtl: false },
    { code: 'ti', name: 'Tigrinya', nativeName: 'ትግርኛ', rtl: false },
    { code: 'ts', name: 'Tsonga', nativeName: 'Xitsonga', rtl: false },
    { code: 'tt', name: 'Tatar', nativeName: 'Татар', rtl: false },
    { code: 'ug', name: 'Uyghur', nativeName: 'ئۇيغۇرچە', rtl: true },
    { code: 've', name: 'Venda', nativeName: 'Tshivenḓa', rtl: false },
    { code: 'wo', name: 'Wolof', nativeName: 'Wolof', rtl: false },
    { code: 'as', name: 'Assamese', nativeName: 'অসমীয়া', rtl: false },
    { code: 'ay', name: 'Aymara', nativeName: 'Aymar Aru', rtl: false },
    { code: 'bm', name: 'Bambara', nativeName: 'Bamanankan', rtl: false },
    { code: 'dv', name: 'Dhivehi', nativeName: 'ދިވެހި', rtl: true },
    { code: 'ee', name: 'Ewe', nativeName: 'Eʋegbe', rtl: false },
    { code: 'gn', name: 'Guarani', nativeName: 'Avañe\'ẽ', rtl: false },
    { code: 'ik', name: 'Inupiaq', nativeName: 'Iñupiatun', rtl: false },
    { code: 'kri', name: 'Krio', nativeName: 'Krio', rtl: false },
    { code: 'ks', name: 'Kashmiri', nativeName: 'कश्मीरी', rtl: false },
    { code: 'kr', name: 'Kanuri', nativeName: 'Kanuri', rtl: false },
    { code: 'mh', name: 'Marshallese', nativeName: 'Kajin M̧ajeļ', rtl: false },
    { code: 'nv', name: 'Navajo', nativeName: 'Diné Bizaad', rtl: false },
    { code: 'nd', name: 'North Ndebele', nativeName: 'isiNdebele', rtl: false },
    { code: 'nr', name: 'South Ndebele', nativeName: 'isiNdebele', rtl: false },
    { code: 'ng', name: 'Ndonga', nativeName: 'Owambo', rtl: false },
    { code: 'oc', name: 'Occitan', nativeName: 'Occitan', rtl: false },
    { code: 'os', name: 'Ossetian', nativeName: 'Ирон', rtl: false },
    { code: 'pi', name: 'Pali', nativeName: 'पालि', rtl: false },
    { code: 'rm', name: 'Romansh', nativeName: 'Rumantsch', rtl: false },
    { code: 'sg', name: 'Sango', nativeName: 'Sängö', rtl: false },
    { code: 'ss', name: 'Swati', nativeName: 'SiSwati', rtl: false },
    { code: 'tn', name: 'Tswana', nativeName: 'Setswana', rtl: false },
    { code: 'to', name: 'Tonga', nativeName: 'Lea Faka-Tonga', rtl: false },
    { code: 'tw', name: 'Twi', nativeName: 'Twi', rtl: false },
    { code: 'ty', name: 'Tahitian', nativeName: 'Reo Tahiti', rtl: false },
    { code: 'wa', name: 'Walloon', nativeName: 'Walon', rtl: false },
    { code: 'za', name: 'Zhuang', nativeName: 'Cuengh', rtl: false }
];

/**
 * Get language by code
 * @param {string} code - ISO 639-1 language code
 * @returns {Object|null} Language object or null
 */
export const getLanguageByCode = (code) => {
    return WORLD_LANGUAGES.find(lang => lang.code === code) || null;
};

/**
 * Check if language is RTL
 * @param {string} code - ISO 639-1 language code
 * @returns {boolean} True if RTL, false otherwise
 */
export const isLanguageRTL = (code) => {
    const lang = getLanguageByCode(code);
    return lang ? lang.rtl : false;
};
