/**
 * Timezone names in multiple languages
 * Shared between frontend and backend
 * 
 * This provides human-readable names for all IANA timezones
 */

export const TIMEZONE_NAMES = {
    // Africa
    'Africa/Abidjan': { ar: 'أبيدجان', en: 'Abidjan', fr: 'Abidjan' },
    'Africa/Accra': { ar: 'أكرا', en: 'Accra', fr: 'Accra' },
    'Africa/Addis_Ababa': { ar: 'أديس أبابا', en: 'Addis Ababa', fr: 'Addis-Abeba' },
    'Africa/Algiers': { ar: 'الجزائر', en: 'Algiers', fr: 'Alger' },
    'Africa/Asmara': { ar: 'أسمرة', en: 'Asmara', fr: 'Asmara' },
    'Africa/Bamako': { ar: 'باماكو', en: 'Bamako', fr: 'Bamako' },
    'Africa/Bangui': { ar: 'بانغي', en: 'Bangui', fr: 'Bangui' },
    'Africa/Banjul': { ar: 'بانجول', en: 'Banjul', fr: 'Banjul' },
    'Africa/Bissau': { ar: 'بيساو', en: 'Bissau', fr: 'Bissau' },
    'Africa/Blantyre': { ar: 'بلانتاير', en: 'Blantyre', fr: 'Blantyre' },
    'Africa/Brazzaville': { ar: 'برازافيل', en: 'Brazzaville', fr: 'Brazzaville' },
    'Africa/Bujumbura': { ar: 'بوجمبورا', en: 'Bujumbura', fr: 'Bujumbura' },
    'Africa/Cairo': { ar: 'القاهرة', en: 'Cairo', fr: 'Le Caire' },
    'Africa/Casablanca': { ar: 'الدار البيضاء', en: 'Casablanca', fr: 'Casablanca' },
    'Africa/Ceuta': { ar: 'سبتة', en: 'Ceuta', fr: 'Ceuta' },
    'Africa/Conakry': { ar: 'كوناكري', en: 'Conakry', fr: 'Conakry' },
    'Africa/Dakar': { ar: 'داكار', en: 'Dakar', fr: 'Dakar' },
    'Africa/Dar_es_Salaam': { ar: 'دار السلام', en: 'Dar es Salaam', fr: 'Dar es Salaam' },
    'Africa/Djibouti': { ar: 'جيبوتي', en: 'Djibouti', fr: 'Djibouti' },
    'Africa/Douala': { ar: 'دوالا', en: 'Douala', fr: 'Douala' },
    'Africa/El_Aaiun': { ar: 'العيون', en: 'El Aaiun', fr: 'Laâyoune' },
    'Africa/Freetown': { ar: 'فريتاون', en: 'Freetown', fr: 'Freetown' },
    'Africa/Gaborone': { ar: 'غابورون', en: 'Gaborone', fr: 'Gaborone' },
    'Africa/Harare': { ar: 'هراري', en: 'Harare', fr: 'Harare' },
    'Africa/Johannesburg': { ar: 'جوهانسبرغ', en: 'Johannesburg', fr: 'Johannesburg' },
    'Africa/Juba': { ar: 'جوبا', en: 'Juba', fr: 'Djouba' },
    'Africa/Kampala': { ar: 'كمبالا', en: 'Kampala', fr: 'Kampala' },
    'Africa/Khartoum': { ar: 'الخرطوم', en: 'Khartoum', fr: 'Khartoum' },
    'Africa/Kigali': { ar: 'كيغالي', en: 'Kigali', fr: 'Kigali' },
    'Africa/Kinshasa': { ar: 'كينشاسا', en: 'Kinshasa', fr: 'Kinshasa' },
    'Africa/Lagos': { ar: 'لاغوس', en: 'Lagos', fr: 'Lagos' },
    'Africa/Libreville': { ar: 'ليبرفيل', en: 'Libreville', fr: 'Libreville' },
    'Africa/Lome': { ar: 'لومي', en: 'Lome', fr: 'Lomé' },
    'Africa/Luanda': { ar: 'لواندا', en: 'Luanda', fr: 'Luanda' },
    'Africa/Lubumbashi': { ar: 'لوبومباشي', en: 'Lubumbashi', fr: 'Lubumbashi' },
    'Africa/Lusaka': { ar: 'لوساكا', en: 'Lusaka', fr: 'Lusaka' },
    'Africa/Malabo': { ar: 'مالابو', en: 'Malabo', fr: 'Malabo' },
    'Africa/Maputo': { ar: 'مابوتو', en: 'Maputo', fr: 'Maputo' },
    'Africa/Maseru': { ar: 'ماسيرو', en: 'Maseru', fr: 'Maseru' },
    'Africa/Mbabane': { ar: 'مبابان', en: 'Mbabane', fr: 'Mbabane' },
    'Africa/Mogadishu': { ar: 'مقديشو', en: 'Mogadishu', fr: 'Mogadiscio' },
    'Africa/Monrovia': { ar: 'مونروفيا', en: 'Monrovia', fr: 'Monrovia' },
    'Africa/Nairobi': { ar: 'نيروبي', en: 'Nairobi', fr: 'Nairobi' },
    'Africa/Ndjamena': { ar: 'نجامينا', en: 'Ndjamena', fr: 'Ndjamena' },
    'Africa/Niamey': { ar: 'نيامي', en: 'Niamey', fr: 'Niamey' },
    'Africa/Nouakchott': { ar: 'نواكشوط', en: 'Nouakchott', fr: 'Nouakchott' },
    'Africa/Ouagadougou': { ar: 'واغادوغو', en: 'Ouagadougou', fr: 'Ouagadougou' },
    'Africa/Porto-Novo': { ar: 'بورتو نوفو', en: 'Porto-Novo', fr: 'Porto-Novo' },
    'Africa/Sao_Tome': { ar: 'ساو تومي', en: 'Sao Tome', fr: 'São Tomé' },
    'Africa/Tripoli': { ar: 'طرابلس', en: 'Tripoli', fr: 'Tripoli' },
    'Africa/Tunis': { ar: 'تونس', en: 'Tunis', fr: 'Tunis' },
    'Africa/Windhoek': { ar: 'ويندهوك', en: 'Windhoek', fr: 'Windhoek' },
    
    // America
    'America/Adak': { ar: 'أداك', en: 'Adak', fr: 'Adak' },
    'America/Anchorage': { ar: 'أنكوريج', en: 'Anchorage', fr: 'Anchorage' },
    'America/Anguilla': { ar: 'أنغويلا', en: 'Anguilla', fr: 'Anguilla' },
    'America/Antigua': { ar: 'أنتيغوا', en: 'Antigua', fr: 'Antigua' },
    'America/Araguaina': { ar: 'أراغواينا', en: 'Araguaina', fr: 'Araguaina' },
    'America/Argentina/Buenos_Aires': { ar: 'بوينس آيرس', en: 'Buenos Aires', fr: 'Buenos Aires' },
    'America/Argentina/Catamarca': { ar: 'كاتاماركا', en: 'Catamarca', fr: 'Catamarca' },
    'America/Argentina/Cordoba': { ar: 'قرطبة', en: 'Cordoba', fr: 'Córdoba' },
    'America/Argentina/Jujuy': { ar: 'خوخوي', en: 'Jujuy', fr: 'Jujuy' },
    'America/Argentina/La_Rioja': { ar: 'لا ريوخا', en: 'La Rioja', fr: 'La Rioja' },
    'America/Argentina/Mendoza': { ar: 'ميندوزا', en: 'Mendoza', fr: 'Mendoza' },
    'America/Argentina/Rio_Gallegos': { ar: 'ريو غاليغوس', en: 'Rio Gallegos', fr: 'Río Gallegos' },
    'America/Argentina/Salta': { ar: 'سالتا', en: 'Salta', fr: 'Salta' },
    'America/Argentina/San_Juan': { ar: 'سان خوان', en: 'San Juan', fr: 'San Juan' },
    'America/Argentina/San_Luis': { ar: 'سان لويس', en: 'San Luis', fr: 'San Luis' },
    'America/Argentina/Tucuman': { ar: 'توكومان', en: 'Tucuman', fr: 'Tucumán' },
    'America/Argentina/Ushuaia': { ar: 'أوشوايا', en: 'Ushuaia', fr: 'Ushuaia' },
    'America/Aruba': { ar: 'أروبا', en: 'Aruba', fr: 'Aruba' },
    'America/Asuncion': { ar: 'أسونسيون', en: 'Asuncion', fr: 'Asunción' },
    'America/Atikokan': { ar: 'أتيكوكان', en: 'Atikokan', fr: 'Atikokan' },
    'America/Bahia': { ar: 'باهيا', en: 'Bahia', fr: 'Bahia' },
    'America/Bahia_Banderas': { ar: 'باهيا بانديراس', en: 'Bahia Banderas', fr: 'Bahia Banderas' },
    'America/Barbados': { ar: 'بربادوس', en: 'Barbados', fr: 'Barbade' },
    'America/Belem': { ar: 'بيليم', en: 'Belem', fr: 'Belém' },
    'America/Belize': { ar: 'بليز', en: 'Belize', fr: 'Belize' },
    'America/Blanc-Sablon': { ar: 'بلان سابلون', en: 'Blanc-Sablon', fr: 'Blanc-Sablon' },
    'America/Boa_Vista': { ar: 'بوا فيستا', en: 'Boa Vista', fr: 'Boa Vista' },
    'America/Bogota': { ar: 'بوغوتا', en: 'Bogota', fr: 'Bogota' },
    'America/Boise': { ar: 'بويسي', en: 'Boise', fr: 'Boise' },
    'America/Cambridge_Bay': { ar: 'كامبريدج باي', en: 'Cambridge Bay', fr: 'Cambridge Bay' },
    'America/Campo_Grande': { ar: 'كامبو غراندي', en: 'Campo Grande', fr: 'Campo Grande' },
    'America/Cancun': { ar: 'كانكون', en: 'Cancun', fr: 'Cancún' },
    'America/Caracas': { ar: 'كاراكاس', en: 'Caracas', fr: 'Caracas' },
    'America/Cayenne': { ar: 'كايين', en: 'Cayenne', fr: 'Cayenne' },
    'America/Cayman': { ar: 'كايمان', en: 'Cayman', fr: 'Caïmans' },
    'America/Chicago': { ar: 'شيكاغو', en: 'Chicago', fr: 'Chicago' },
    'America/Chihuahua': { ar: 'تشيهواهوا', en: 'Chihuahua', fr: 'Chihuahua' },
    'America/Costa_Rica': { ar: 'كوستاريكا', en: 'Costa Rica', fr: 'Costa Rica' },
    'America/Creston': { ar: 'كريستون', en: 'Creston', fr: 'Creston' },
    'America/Cuiaba': { ar: 'كويابا', en: 'Cuiaba', fr: 'Cuiabá' },
    'America/Curacao': { ar: 'كوراساو', en: 'Curacao', fr: 'Curaçao' },
    'America/Danmarkshavn': { ar: 'دانماركشافن', en: 'Danmarkshavn', fr: 'Danmarkshavn' },
    'America/Dawson': { ar: 'داوسون', en: 'Dawson', fr: 'Dawson' },
    'America/Dawson_Creek': { ar: 'داوسون كريك', en: 'Dawson Creek', fr: 'Dawson Creek' },
    'America/Denver': { ar: 'دنفر', en: 'Denver', fr: 'Denver' },
    'America/Detroit': { ar: 'ديترويت', en: 'Detroit', fr: 'Détroit' },
    'America/Dominica': { ar: 'دومينيكا', en: 'Dominica', fr: 'Dominique' },
    'America/Edmonton': { ar: 'إدمونتون', en: 'Edmonton', fr: 'Edmonton' },
    'America/Eirunepe': { ar: 'إيرونيبي', en: 'Eirunepe', fr: 'Eirunepé' },
    'America/El_Salvador': { ar: 'السلفادور', en: 'El Salvador', fr: 'Salvador' },
    'America/Fort_Nelson': { ar: 'فورت نيلسون', en: 'Fort Nelson', fr: 'Fort Nelson' },
    'America/Fortaleza': { ar: 'فورتاليزا', en: 'Fortaleza', fr: 'Fortaleza' },
    'America/Glace_Bay': { ar: 'غلاس باي', en: 'Glace Bay', fr: 'Glace Bay' },
    'America/Godthab': { ar: 'نوك', en: 'Nuuk', fr: 'Nuuk' },
    'America/Goose_Bay': { ar: 'غوس باي', en: 'Goose Bay', fr: 'Goose Bay' },
    'America/Grand_Turk': { ar: 'غراند تورك', en: 'Grand Turk', fr: 'Grand Turk' },
    'America/Grenada': { ar: 'غرينادا', en: 'Grenada', fr: 'Grenade' },
    'America/Guadeloupe': { ar: 'غوادلوب', en: 'Guadeloupe', fr: 'Guadeloupe' },
    'America/Guatemala': { ar: 'غواتيمالا', en: 'Guatemala', fr: 'Guatemala' },
    'America/Guayaquil': { ar: 'غواياكيل', en: 'Guayaquil', fr: 'Guayaquil' },
    'America/Guyana': { ar: 'غيانا', en: 'Guyana', fr: 'Guyana' },
    'America/Halifax': { ar: 'هاليفاكس', en: 'Halifax', fr: 'Halifax' },
    'America/Havana': { ar: 'هافانا', en: 'Havana', fr: 'La Havane' },
    'America/Hermosillo': { ar: 'هيرموسيو', en: 'Hermosillo', fr: 'Hermosillo' },
    'America/Indiana/Indianapolis': { ar: 'إنديانابوليس', en: 'Indianapolis', fr: 'Indianapolis' },
    'America/Indiana/Knox': { ar: 'نوكس', en: 'Knox', fr: 'Knox' },
    'America/Indiana/Marengo': { ar: 'مارينغو', en: 'Marengo', fr: 'Marengo' },
    'America/Indiana/Petersburg': { ar: 'بيترسبرغ', en: 'Petersburg', fr: 'Petersburg' },
    'America/Indiana/Tell_City': { ar: 'تيل سيتي', en: 'Tell City', fr: 'Tell City' },
    'America/Indiana/Vevay': { ar: 'فيفاي', en: 'Vevay', fr: 'Vevay' },
    'America/Indiana/Vincennes': { ar: 'فينسينس', en: 'Vincennes', fr: 'Vincennes' },
    'America/Indiana/Winamac': { ar: 'ويناماك', en: 'Winamac', fr: 'Winamac' },
    'America/Inuvik': { ar: 'إنوفيك', en: 'Inuvik', fr: 'Inuvik' },
    'America/Iqaluit': { ar: 'إيكالويت', en: 'Iqaluit', fr: 'Iqaluit' },
    'America/Jamaica': { ar: 'جامايكا', en: 'Jamaica', fr: 'Jamaïque' },
    'America/Juneau': { ar: 'جونو', en: 'Juneau', fr: 'Juneau' },
    'America/Kentucky/Louisville': { ar: 'لويفيل', en: 'Louisville', fr: 'Louisville' },
    'America/Kentucky/Monticello': { ar: 'مونتيسيلو', en: 'Monticello', fr: 'Monticello' },
    'America/Kralendijk': { ar: 'كرالنديك', en: 'Kralendijk', fr: 'Kralendijk' },
    'America/La_Paz': { ar: 'لاباز', en: 'La Paz', fr: 'La Paz' },
    'America/Lima': { ar: 'ليما', en: 'Lima', fr: 'Lima' },
    'America/Los_Angeles': { ar: 'لوس أنجلوس', en: 'Los Angeles', fr: 'Los Angeles' },
    'America/Lower_Princes': { ar: 'لوار برينسيس', en: 'Lower Princes', fr: 'Lower Princes' },
    'America/Maceio': { ar: 'ماسيو', en: 'Maceio', fr: 'Maceió' },
    'America/Managua': { ar: 'ماناغوا', en: 'Managua', fr: 'Managua' },
    'America/Manaus': { ar: 'ماناوس', en: 'Manaus', fr: 'Manaus' },
    'America/Marigot': { ar: 'ماريغوت', en: 'Marigot', fr: 'Marigot' },
    'America/Martinique': { ar: 'مارتينيك', en: 'Martinique', fr: 'Martinique' },
    'America/Matamoros': { ar: 'ماتاموروس', en: 'Matamoros', fr: 'Matamoros' },
    'America/Mazatlan': { ar: 'مازاتلان', en: 'Mazatlan', fr: 'Mazatlán' },
    'America/Menominee': { ar: 'مينوميني', en: 'Menominee', fr: 'Menominee' },
    'America/Merida': { ar: 'ميريدا', en: 'Merida', fr: 'Mérida' },
    'America/Metlakatla': { ar: 'ميتلاكاتلا', en: 'Metlakatla', fr: 'Metlakatla' },
    'America/Mexico_City': { ar: 'مكسيكو سيتي', en: 'Mexico City', fr: 'Mexico' },
    'America/Miquelon': { ar: 'ميكلون', en: 'Miquelon', fr: 'Miquelon' },
    'America/Moncton': { ar: 'مونكتون', en: 'Moncton', fr: 'Moncton' },
    'America/Monterrey': { ar: 'مونتيري', en: 'Monterrey', fr: 'Monterrey' },
    'America/Montevideo': { ar: 'مونتيفيديو', en: 'Montevideo', fr: 'Montevideo' },
    'America/Montserrat': { ar: 'مونتسيرات', en: 'Montserrat', fr: 'Montserrat' },
    'America/Nassau': { ar: 'ناساو', en: 'Nassau', fr: 'Nassau' },
    'America/New_York': { ar: 'نيويورك', en: 'New York', fr: 'New York' },
    'America/Nipigon': { ar: 'نيبيغون', en: 'Nipigon', fr: 'Nipigon' },
    'America/Nome': { ar: 'نوم', en: 'Nome', fr: 'Nome' },
    'America/Noronha': { ar: 'نورونها', en: 'Noronha', fr: 'Noronha' },
    'America/North_Dakota/Beulah': { ar: 'بيولا', en: 'Beulah', fr: 'Beulah' },
    'America/North_Dakota/Center': { ar: 'سنتر', en: 'Center', fr: 'Center' },
    'America/North_Dakota/New_Salem': { ar: 'نيو سالم', en: 'New Salem', fr: 'New Salem' },
    'America/Ojinaga': { ar: 'أوخيناغا', en: 'Ojinaga', fr: 'Ojinaga' },
    'America/Panama': { ar: 'بنما', en: 'Panama', fr: 'Panama' },
    'America/Pangnirtung': { ar: 'بانغنيرتونغ', en: 'Pangnirtung', fr: 'Pangnirtung' },
    'America/Paramaribo': { ar: 'باراماريبو', en: 'Paramaribo', fr: 'Paramaribo' },
    'America/Phoenix': { ar: 'فينيكس', en: 'Phoenix', fr: 'Phoenix' },
    'America/Port-au-Prince': { ar: 'بورت أو برنس', en: 'Port-au-Prince', fr: 'Port-au-Prince' },
    'America/Port_of_Spain': { ar: 'بورت أوف سبين', en: 'Port of Spain', fr: 'Port-d\'Espagne' },
    'America/Porto_Velho': { ar: 'بورتو فيلهو', en: 'Porto Velho', fr: 'Porto Velho' },
    'America/Puerto_Rico': { ar: 'بورتوريكو', en: 'Puerto Rico', fr: 'Porto Rico' },
    'America/Punta_Arenas': { ar: 'بونتا أريناس', en: 'Punta Arenas', fr: 'Punta Arenas' },
    'America/Rainy_River': { ar: 'ريني ريفر', en: 'Rainy River', fr: 'Rainy River' },
    'America/Rankin_Inlet': { ar: 'رانكين إنليت', en: 'Rankin Inlet', fr: 'Rankin Inlet' },
    'America/Recife': { ar: 'ريسيفي', en: 'Recife', fr: 'Recife' },
    'America/Regina': { ar: 'ريجاينا', en: 'Regina', fr: 'Regina' },
    'America/Resolute': { ar: 'ريزوليوت', en: 'Resolute', fr: 'Resolute' },
    'America/Rio_Branco': { ar: 'ريو برانكو', en: 'Rio Branco', fr: 'Rio Branco' },
    'America/Santarem': { ar: 'سانتاريم', en: 'Santarem', fr: 'Santarém' },
    'America/Santiago': { ar: 'سانتياغو', en: 'Santiago', fr: 'Santiago' },
    'America/Santo_Domingo': { ar: 'سانتو دومينغو', en: 'Santo Domingo', fr: 'Saint-Domingue' },
    'America/Sao_Paulo': { ar: 'ساو باولو', en: 'Sao Paulo', fr: 'São Paulo' },
    'America/Scoresbysund': { ar: 'سكورسبيسوند', en: 'Scoresbysund', fr: 'Scoresbysund' },
    'America/Sitka': { ar: 'سيتكا', en: 'Sitka', fr: 'Sitka' },
    'America/St_Barthelemy': { ar: 'سان بارتيليمي', en: 'St Barthelemy', fr: 'Saint-Barthélemy' },
    'America/St_Johns': { ar: 'سانت جونز', en: 'St Johns', fr: 'Saint-Jean' },
    'America/St_Kitts': { ar: 'سانت كيتس', en: 'St Kitts', fr: 'Saint-Kitts' },
    'America/St_Lucia': { ar: 'سانت لوسيا', en: 'St Lucia', fr: 'Sainte-Lucie' },
    'America/St_Thomas': { ar: 'سانت توماس', en: 'St Thomas', fr: 'Saint-Thomas' },
    'America/St_Vincent': { ar: 'سانت فنسنت', en: 'St Vincent', fr: 'Saint-Vincent' },
    'America/Swift_Current': { ar: 'سويفت كارنت', en: 'Swift Current', fr: 'Swift Current' },
    'America/Tegucigalpa': { ar: 'تيغوسيغالبا', en: 'Tegucigalpa', fr: 'Tegucigalpa' },
    'America/Thule': { ar: 'ثول', en: 'Thule', fr: 'Thulé' },
    'America/Thunder_Bay': { ar: 'ثاندر باي', en: 'Thunder Bay', fr: 'Thunder Bay' },
    'America/Tijuana': { ar: 'تيخوانا', en: 'Tijuana', fr: 'Tijuana' },
    'America/Toronto': { ar: 'تورونتو', en: 'Toronto', fr: 'Toronto' },
    'America/Tortola': { ar: 'تورتولا', en: 'Tortola', fr: 'Tortola' },
    'America/Vancouver': { ar: 'فانكوفر', en: 'Vancouver', fr: 'Vancouver' },
    'America/Whitehorse': { ar: 'وايت هورس', en: 'Whitehorse', fr: 'Whitehorse' },
    'America/Winnipeg': { ar: 'وينيبيغ', en: 'Winnipeg', fr: 'Winnipeg' },
    'America/Yakutat': { ar: 'ياكوتات', en: 'Yakutat', fr: 'Yakutat' },
    'America/Yellowknife': { ar: 'يلونايف', en: 'Yellowknife', fr: 'Yellowknife' },
    
    // Antarctica
    'Antarctica/Casey': { ar: 'كيسي', en: 'Casey', fr: 'Casey' },
    'Antarctica/Davis': { ar: 'ديفيس', en: 'Davis', fr: 'Davis' },
    'Antarctica/DumontDUrville': { ar: 'دومون دورفيل', en: 'Dumont d\'Urville', fr: 'Dumont d\'Urville' },
    'Antarctica/Macquarie': { ar: 'ماكواري', en: 'Macquarie', fr: 'Macquarie' },
    'Antarctica/Mawson': { ar: 'ماوسون', en: 'Mawson', fr: 'Mawson' },
    'Antarctica/McMurdo': { ar: 'ماكموردو', en: 'McMurdo', fr: 'McMurdo' },
    'Antarctica/Palmer': { ar: 'بالمر', en: 'Palmer', fr: 'Palmer' },
    'Antarctica/Rothera': { ar: 'روثيرا', en: 'Rothera', fr: 'Rothera' },
    'Antarctica/Syowa': { ar: 'سيووا', en: 'Syowa', fr: 'Syowa' },
    'Antarctica/Troll': { ar: 'ترول', en: 'Troll', fr: 'Troll' },
    'Antarctica/Vostok': { ar: 'فوستوك', en: 'Vostok', fr: 'Vostok' },
    
    // Arctic
    'Arctic/Longyearbyen': { ar: 'لونغييربين', en: 'Longyearbyen', fr: 'Longyearbyen' },
    
    // Asia
    'Asia/Aden': { ar: 'عدن', en: 'Aden', fr: 'Aden' },
    'Asia/Almaty': { ar: 'ألماتي', en: 'Almaty', fr: 'Almaty' },
    'Asia/Amman': { ar: 'عمان', en: 'Amman', fr: 'Amman' },
    'Asia/Anadyr': { ar: 'أنادير', en: 'Anadyr', fr: 'Anadyr' },
    'Asia/Aqtau': { ar: 'أكتاو', en: 'Aqtau', fr: 'Aqtaou' },
    'Asia/Aqtobe': { ar: 'أكتوبي', en: 'Aqtobe', fr: 'Aqtöbe' },
    'Asia/Ashgabat': { ar: 'عشق آباد', en: 'Ashgabat', fr: 'Achgabat' },
    'Asia/Atyrau': { ar: 'أتيراو', en: 'Atyrau', fr: 'Atyraou' },
    'Asia/Baghdad': { ar: 'بغداد', en: 'Baghdad', fr: 'Bagdad' },
    'Asia/Bahrain': { ar: 'البحرين', en: 'Bahrain', fr: 'Bahreïn' },
    'Asia/Baku': { ar: 'باكو', en: 'Baku', fr: 'Bakou' },
    'Asia/Bangkok': { ar: 'بانكوك', en: 'Bangkok', fr: 'Bangkok' },
    'Asia/Barnaul': { ar: 'بارناول', en: 'Barnaul', fr: 'Barnaoul' },
    'Asia/Beirut': { ar: 'بيروت', en: 'Beirut', fr: 'Beyrouth' },
    'Asia/Bishkek': { ar: 'بيشكيك', en: 'Bishkek', fr: 'Bichkek' },
    'Asia/Brunei': { ar: 'بروناي', en: 'Brunei', fr: 'Brunei' },
    'Asia/Chita': { ar: 'تشيتا', en: 'Chita', fr: 'Tchita' },
    'Asia/Choibalsan': { ar: 'تشويبالسان', en: 'Choibalsan', fr: 'Tchoïbalsan' },
    'Asia/Colombo': { ar: 'كولومبو', en: 'Colombo', fr: 'Colombo' },
    'Asia/Damascus': { ar: 'دمشق', en: 'Damascus', fr: 'Damas' },
    'Asia/Dhaka': { ar: 'دكا', en: 'Dhaka', fr: 'Dacca' },
    'Asia/Dili': { ar: 'ديلي', en: 'Dili', fr: 'Dili' },
    'Asia/Dubai': { ar: 'دبي', en: 'Dubai', fr: 'Dubaï' },
    'Asia/Dushanbe': { ar: 'دوشنبه', en: 'Dushanbe', fr: 'Douchanbé' },
    'Asia/Famagusta': { ar: 'فاماغوستا', en: 'Famagusta', fr: 'Famagouste' },
    'Asia/Gaza': { ar: 'غزة', en: 'Gaza', fr: 'Gaza' },
    'Asia/Hebron': { ar: 'الخليل', en: 'Hebron', fr: 'Hébron' },
    'Asia/Ho_Chi_Minh': { ar: 'هوشي منه', en: 'Ho Chi Minh', fr: 'Hô-Chi-Minh-Ville' },
    'Asia/Hong_Kong': { ar: 'هونغ كونغ', en: 'Hong Kong', fr: 'Hong Kong' },
    'Asia/Hovd': { ar: 'هوفد', en: 'Hovd', fr: 'Hovd' },
    'Asia/Irkutsk': { ar: 'إيركوتسك', en: 'Irkutsk', fr: 'Irkoutsk' },
    'Asia/Jakarta': { ar: 'جاكرتا', en: 'Jakarta', fr: 'Jakarta' },
    'Asia/Jayapura': { ar: 'جايابورا', en: 'Jayapura', fr: 'Jayapura' },
    'Asia/Jerusalem': { ar: 'القدس', en: 'Jerusalem', fr: 'Jérusalem' },
    'Asia/Kabul': { ar: 'كابول', en: 'Kabul', fr: 'Kaboul' },
    'Asia/Kamchatka': { ar: 'كامتشاتكا', en: 'Kamchatka', fr: 'Kamtchatka' },
    'Asia/Karachi': { ar: 'كراتشي', en: 'Karachi', fr: 'Karachi' },
    'Asia/Kathmandu': { ar: 'كاتماندو', en: 'Kathmandu', fr: 'Katmandou' },
    'Asia/Khandyga': { ar: 'خانديغا', en: 'Khandyga', fr: 'Khandyga' },
    'Asia/Kolkata': { ar: 'كولكاتا', en: 'Kolkata', fr: 'Calcutta' },
    'Asia/Krasnoyarsk': { ar: 'كراسنويارسك', en: 'Krasnoyarsk', fr: 'Krasnoïarsk' },
    'Asia/Kuala_Lumpur': { ar: 'كوالالمبور', en: 'Kuala Lumpur', fr: 'Kuala Lumpur' },
    'Asia/Kuching': { ar: 'كوتشينغ', en: 'Kuching', fr: 'Kuching' },
    'Asia/Kuwait': { ar: 'الكويت', en: 'Kuwait', fr: 'Koweït' },
    'Asia/Macau': { ar: 'ماكاو', en: 'Macau', fr: 'Macao' },
    'Asia/Magadan': { ar: 'ماغادان', en: 'Magadan', fr: 'Magadan' },
    'Asia/Makassar': { ar: 'ماكاسار', en: 'Makassar', fr: 'Makassar' },
    'Asia/Manila': { ar: 'مانيلا', en: 'Manila', fr: 'Manille' },
    'Asia/Muscat': { ar: 'مسقط', en: 'Muscat', fr: 'Mascate' },
    'Asia/Nicosia': { ar: 'نيقوسيا', en: 'Nicosia', fr: 'Nicosie' },
    'Asia/Novokuznetsk': { ar: 'نوفوكوزنتسك', en: 'Novokuznetsk', fr: 'Novokouznetsk' },
    'Asia/Novosibirsk': { ar: 'نوفوسيبيرسك', en: 'Novosibirsk', fr: 'Novossibirsk' },
    'Asia/Omsk': { ar: 'أومسك', en: 'Omsk', fr: 'Omsk' },
    'Asia/Oral': { ar: 'أورال', en: 'Oral', fr: 'Ouralsk' },
    'Asia/Phnom_Penh': { ar: 'بنوم بنه', en: 'Phnom Penh', fr: 'Phnom Penh' },
    'Asia/Pontianak': { ar: 'بونتياناك', en: 'Pontianak', fr: 'Pontianak' },
    'Asia/Pyongyang': { ar: 'بيونغ يانغ', en: 'Pyongyang', fr: 'Pyongyang' },
    'Asia/Qatar': { ar: 'قطر', en: 'Qatar', fr: 'Qatar' },
    'Asia/Qostanay': { ar: 'كوستاناي', en: 'Qostanay', fr: 'Kostanaï' },
    'Asia/Qyzylorda': { ar: 'كيزيلوردا', en: 'Qyzylorda', fr: 'Kyzylorda' },
    'Asia/Riyadh': { ar: 'الرياض', en: 'Riyadh', fr: 'Riyad' },
    'Asia/Sakhalin': { ar: 'سخالين', en: 'Sakhalin', fr: 'Sakhaline' },
    'Asia/Samarkand': { ar: 'سمرقند', en: 'Samarkand', fr: 'Samarcande' },
    'Asia/Seoul': { ar: 'سيول', en: 'Seoul', fr: 'Séoul' },
    'Asia/Shanghai': { ar: 'شنغهاي', en: 'Shanghai', fr: 'Shanghai' },
    'Asia/Singapore': { ar: 'سنغافورة', en: 'Singapore', fr: 'Singapour' },
    'Asia/Srednekolymsk': { ar: 'سريدنيكوليمسك', en: 'Srednekolymsk', fr: 'Srednekolymsk' },
    'Asia/Taipei': { ar: 'تايبيه', en: 'Taipei', fr: 'Taipei' },
    'Asia/Tashkent': { ar: 'طشقند', en: 'Tashkent', fr: 'Tachkent' },
    'Asia/Tbilisi': { ar: 'تبليسي', en: 'Tbilisi', fr: 'Tbilissi' },
    'Asia/Tehran': { ar: 'طهران', en: 'Tehran', fr: 'Téhéran' },
    'Asia/Thimphu': { ar: 'تيمفو', en: 'Thimphu', fr: 'Thimphou' },
    'Asia/Tokyo': { ar: 'طوكيو', en: 'Tokyo', fr: 'Tokyo' },
    'Asia/Tomsk': { ar: 'تومسك', en: 'Tomsk', fr: 'Tomsk' },
    'Asia/Ulaanbaatar': { ar: 'أولان باتور', en: 'Ulaanbaatar', fr: 'Oulan-Bator' },
    'Asia/Urumqi': { ar: 'أورومتشي', en: 'Urumqi', fr: 'Ürümqi' },
    'Asia/Ust-Nera': { ar: 'أوست نيرا', en: 'Ust-Nera', fr: 'Oust-Nera' },
    'Asia/Vientiane': { ar: 'فيينتيان', en: 'Vientiane', fr: 'Vientiane' },
    'Asia/Vladivostok': { ar: 'فلاديفوستوك', en: 'Vladivostok', fr: 'Vladivostok' },
    'Asia/Yakutsk': { ar: 'ياكوتسك', en: 'Yakutsk', fr: 'Iakoutsk' },
    'Asia/Yangon': { ar: 'يانغون', en: 'Yangon', fr: 'Rangoun' },
    'Asia/Yekaterinburg': { ar: 'يكاترينبورغ', en: 'Yekaterinburg', fr: 'Iekaterinbourg' },
    'Asia/Yerevan': { ar: 'يريفان', en: 'Yerevan', fr: 'Erevan' },
    
    // Atlantic
    'Atlantic/Azores': { ar: 'الأزور', en: 'Azores', fr: 'Açores' },
    'Atlantic/Bermuda': { ar: 'برمودا', en: 'Bermuda', fr: 'Bermudes' },
    'Atlantic/Canary': { ar: 'جزر الكناري', en: 'Canary Islands', fr: 'Îles Canaries' },
    'Atlantic/Cape_Verde': { ar: 'الرأس الأخضر', en: 'Cape Verde', fr: 'Cap-Vert' },
    'Atlantic/Faroe': { ar: 'جزر فارو', en: 'Faroe Islands', fr: 'Îles Féroé' },
    'Atlantic/Madeira': { ar: 'ماديرا', en: 'Madeira', fr: 'Madère' },
    'Atlantic/Reykjavik': { ar: 'ريكيافيك', en: 'Reykjavik', fr: 'Reykjavik' },
    'Atlantic/South_Georgia': { ar: 'جورجيا الجنوبية', en: 'South Georgia', fr: 'Géorgie du Sud' },
    'Atlantic/St_Helena': { ar: 'سانت هيلينا', en: 'St Helena', fr: 'Sainte-Hélène' },
    'Atlantic/Stanley': { ar: 'ستانلي', en: 'Stanley', fr: 'Stanley' },
    
    // Australia
    'Australia/Adelaide': { ar: 'أديليد', en: 'Adelaide', fr: 'Adélaïde' },
    'Australia/Brisbane': { ar: 'بريزبن', en: 'Brisbane', fr: 'Brisbane' },
    'Australia/Broken_Hill': { ar: 'بروكن هيل', en: 'Broken Hill', fr: 'Broken Hill' },
    'Australia/Currie': { ar: 'كوري', en: 'Currie', fr: 'Currie' },
    'Australia/Darwin': { ar: 'داروين', en: 'Darwin', fr: 'Darwin' },
    'Australia/Eucla': { ar: 'يوكلا', en: 'Eucla', fr: 'Eucla' },
    'Australia/Hobart': { ar: 'هوبارت', en: 'Hobart', fr: 'Hobart' },
    'Australia/Lindeman': { ar: 'ليندمان', en: 'Lindeman', fr: 'Lindeman' },
    'Australia/Lord_Howe': { ar: 'لورد هاو', en: 'Lord Howe', fr: 'Lord Howe' },
    'Australia/Melbourne': { ar: 'ملبورن', en: 'Melbourne', fr: 'Melbourne' },
    'Australia/Perth': { ar: 'بيرث', en: 'Perth', fr: 'Perth' },
    'Australia/Sydney': { ar: 'سيدني', en: 'Sydney', fr: 'Sydney' },
    
    // Europe
    'Europe/Amsterdam': { ar: 'أمستردام', en: 'Amsterdam', fr: 'Amsterdam' },
    'Europe/Andorra': { ar: 'أندورا', en: 'Andorra', fr: 'Andorre' },
    'Europe/Astrakhan': { ar: 'أستراخان', en: 'Astrakhan', fr: 'Astrakhan' },
    'Europe/Athens': { ar: 'أثينا', en: 'Athens', fr: 'Athènes' },
    'Europe/Belgrade': { ar: 'بلغراد', en: 'Belgrade', fr: 'Belgrade' },
    'Europe/Berlin': { ar: 'برلين', en: 'Berlin', fr: 'Berlin' },
    'Europe/Bratislava': { ar: 'براتيسلافا', en: 'Bratislava', fr: 'Bratislava' },
    'Europe/Brussels': { ar: 'بروكسل', en: 'Brussels', fr: 'Bruxelles' },
    'Europe/Bucharest': { ar: 'بوخارست', en: 'Bucharest', fr: 'Bucarest' },
    'Europe/Budapest': { ar: 'بودابست', en: 'Budapest', fr: 'Budapest' },
    'Europe/Busingen': { ar: 'بوزينغن', en: 'Busingen', fr: 'Büsingen' },
    'Europe/Chisinau': { ar: 'كيشيناو', en: 'Chisinau', fr: 'Chișinău' },
    'Europe/Copenhagen': { ar: 'كوبنهاغن', en: 'Copenhagen', fr: 'Copenhague' },
    'Europe/Dublin': { ar: 'دبلن', en: 'Dublin', fr: 'Dublin' },
    'Europe/Gibraltar': { ar: 'جبل طارق', en: 'Gibraltar', fr: 'Gibraltar' },
    'Europe/Guernsey': { ar: 'غيرنزي', en: 'Guernsey', fr: 'Guernesey' },
    'Europe/Helsinki': { ar: 'هلسنكي', en: 'Helsinki', fr: 'Helsinki' },
    'Europe/Isle_of_Man': { ar: 'جزيرة مان', en: 'Isle of Man', fr: 'Île de Man' },
    'Europe/Istanbul': { ar: 'إسطنبول', en: 'Istanbul', fr: 'Istanbul' },
    'Europe/Jersey': { ar: 'جيرسي', en: 'Jersey', fr: 'Jersey' },
    'Europe/Kaliningrad': { ar: 'كالينينغراد', en: 'Kaliningrad', fr: 'Kaliningrad' },
    'Europe/Kiev': { ar: 'كييف', en: 'Kiev', fr: 'Kiev' },
    'Europe/Kirov': { ar: 'كيروف', en: 'Kirov', fr: 'Kirov' },
    'Europe/Lisbon': { ar: 'لشبونة', en: 'Lisbon', fr: 'Lisbonne' },
    'Europe/Ljubljana': { ar: 'ليوبليانا', en: 'Ljubljana', fr: 'Ljubljana' },
    'Europe/London': { ar: 'لندن', en: 'London', fr: 'Londres' },
    'Europe/Luxembourg': { ar: 'لوكسمبورغ', en: 'Luxembourg', fr: 'Luxembourg' },
    'Europe/Madrid': { ar: 'مدريد', en: 'Madrid', fr: 'Madrid' },
    'Europe/Malta': { ar: 'مالطا', en: 'Malta', fr: 'Malte' },
    'Europe/Mariehamn': { ar: 'ماريهامن', en: 'Mariehamn', fr: 'Mariehamn' },
    'Europe/Minsk': { ar: 'مينسك', en: 'Minsk', fr: 'Minsk' },
    'Europe/Monaco': { ar: 'موناكو', en: 'Monaco', fr: 'Monaco' },
    'Europe/Moscow': { ar: 'موسكو', en: 'Moscow', fr: 'Moscou' },
    'Europe/Oslo': { ar: 'أوسلو', en: 'Oslo', fr: 'Oslo' },
    'Europe/Paris': { ar: 'باريس', en: 'Paris', fr: 'Paris' },
    'Europe/Podgorica': { ar: 'بودغوريتسا', en: 'Podgorica', fr: 'Podgorica' },
    'Europe/Prague': { ar: 'براغ', en: 'Prague', fr: 'Prague' },
    'Europe/Riga': { ar: 'ريغا', en: 'Riga', fr: 'Riga' },
    'Europe/Rome': { ar: 'روما', en: 'Rome', fr: 'Rome' },
    'Europe/Samara': { ar: 'سامارا', en: 'Samara', fr: 'Samara' },
    'Europe/San_Marino': { ar: 'سان مارينو', en: 'San Marino', fr: 'Saint-Marin' },
    'Europe/Sarajevo': { ar: 'سراييفو', en: 'Sarajevo', fr: 'Sarajevo' },
    'Europe/Saratov': { ar: 'ساراتوف', en: 'Saratov', fr: 'Saratov' },
    'Europe/Simferopol': { ar: 'سيمفيروبول', en: 'Simferopol', fr: 'Simferopol' },
    'Europe/Skopje': { ar: 'سكوبيه', en: 'Skopje', fr: 'Skopje' },
    'Europe/Sofia': { ar: 'صوفيا', en: 'Sofia', fr: 'Sofia' },
    'Europe/Stockholm': { ar: 'ستوكهولم', en: 'Stockholm', fr: 'Stockholm' },
    'Europe/Tallinn': { ar: 'تالين', en: 'Tallinn', fr: 'Tallinn' },
    'Europe/Tirane': { ar: 'تيرانا', en: 'Tirane', fr: 'Tirana' },
    'Europe/Ulyanovsk': { ar: 'أوليانوفسك', en: 'Ulyanovsk', fr: 'Oulianovsk' },
    'Europe/Uzhgorod': { ar: 'أوجغورود', en: 'Uzhgorod', fr: 'Oujhorod' },
    'Europe/Vaduz': { ar: 'فادوز', en: 'Vaduz', fr: 'Vaduz' },
    'Europe/Vatican': { ar: 'الفاتيكان', en: 'Vatican', fr: 'Vatican' },
    'Europe/Vienna': { ar: 'فيينا', en: 'Vienna', fr: 'Vienne' },
    'Europe/Vilnius': { ar: 'فيلنيوس', en: 'Vilnius', fr: 'Vilnius' },
    'Europe/Volgograd': { ar: 'فولغوغراد', en: 'Volgograd', fr: 'Volgograd' },
    'Europe/Warsaw': { ar: 'وارسو', en: 'Warsaw', fr: 'Varsovie' },
    'Europe/Zagreb': { ar: 'زغرب', en: 'Zagreb', fr: 'Zagreb' },
    'Europe/Zaporozhye': { ar: 'زابوروجيه', en: 'Zaporozhye', fr: 'Zaporijia' },
    'Europe/Zurich': { ar: 'زيورخ', en: 'Zurich', fr: 'Zurich' },
    
    // Indian
    'Indian/Antananarivo': { ar: 'أنتاناناريفو', en: 'Antananarivo', fr: 'Antananarivo' },
    'Indian/Chagos': { ar: 'تشاغوس', en: 'Chagos', fr: 'Chagos' },
    'Indian/Christmas': { ar: 'جزيرة الكريسماس', en: 'Christmas Island', fr: 'Île Christmas' },
    'Indian/Cocos': { ar: 'جزر كوكوس', en: 'Cocos Islands', fr: 'Îles Cocos' },
    'Indian/Comoro': { ar: 'جزر القمر', en: 'Comoro', fr: 'Comores' },
    'Indian/Kerguelen': { ar: 'كيرغيلين', en: 'Kerguelen', fr: 'Kerguelen' },
    'Indian/Mahe': { ar: 'ماهي', en: 'Mahe', fr: 'Mahé' },
    'Indian/Maldives': { ar: 'المالديف', en: 'Maldives', fr: 'Maldives' },
    'Indian/Mauritius': { ar: 'موريشيوس', en: 'Mauritius', fr: 'Maurice' },
    'Indian/Mayotte': { ar: 'مايوت', en: 'Mayotte', fr: 'Mayotte' },
    'Indian/Reunion': { ar: 'ريونيون', en: 'Reunion', fr: 'La Réunion' },
    
    // Pacific
    'Pacific/Apia': { ar: 'أبيا', en: 'Apia', fr: 'Apia' },
    'Pacific/Auckland': { ar: 'أوكلاند', en: 'Auckland', fr: 'Auckland' },
    'Pacific/Bougainville': { ar: 'بوغانفيل', en: 'Bougainville', fr: 'Bougainville' },
    'Pacific/Chatham': { ar: 'تشاتام', en: 'Chatham', fr: 'Chatham' },
    'Pacific/Chuuk': { ar: 'تشوك', en: 'Chuuk', fr: 'Chuuk' },
    'Pacific/Easter': { ar: 'جزيرة القيامة', en: 'Easter Island', fr: 'Île de Pâques' },
    'Pacific/Efate': { ar: 'إيفاتي', en: 'Efate', fr: 'Éfaté' },
    'Pacific/Enderbury': { ar: 'إندربري', en: 'Enderbury', fr: 'Enderbury' },
    'Pacific/Fakaofo': { ar: 'فاكاوفو', en: 'Fakaofo', fr: 'Fakaofo' },
    'Pacific/Fiji': { ar: 'فيجي', en: 'Fiji', fr: 'Fidji' },
    'Pacific/Funafuti': { ar: 'فونافوتي', en: 'Funafuti', fr: 'Funafuti' },
    'Pacific/Galapagos': { ar: 'غالاباغوس', en: 'Galapagos', fr: 'Galápagos' },
    'Pacific/Gambier': { ar: 'غامبير', en: 'Gambier', fr: 'Gambier' },
    'Pacific/Guadalcanal': { ar: 'غوادالكانال', en: 'Guadalcanal', fr: 'Guadalcanal' },
    'Pacific/Guam': { ar: 'غوام', en: 'Guam', fr: 'Guam' },
    'Pacific/Honolulu': { ar: 'هونولولو', en: 'Honolulu', fr: 'Honolulu' },
    'Pacific/Kiritimati': { ar: 'كيريتيماتي', en: 'Kiritimati', fr: 'Kiritimati' },
    'Pacific/Kosrae': { ar: 'كوسراي', en: 'Kosrae', fr: 'Kosrae' },
    'Pacific/Kwajalein': { ar: 'كواجالين', en: 'Kwajalein', fr: 'Kwajalein' },
    'Pacific/Majuro': { ar: 'ماجورو', en: 'Majuro', fr: 'Majuro' },
    'Pacific/Marquesas': { ar: 'ماركيساس', en: 'Marquesas', fr: 'Marquises' },
    'Pacific/Midway': { ar: 'ميدواي', en: 'Midway', fr: 'Midway' },
    'Pacific/Nauru': { ar: 'ناورو', en: 'Nauru', fr: 'Nauru' },
    'Pacific/Niue': { ar: 'نيوي', en: 'Niue', fr: 'Niue' },
    'Pacific/Norfolk': { ar: 'نورفولك', en: 'Norfolk', fr: 'Norfolk' },
    'Pacific/Noumea': { ar: 'نوميا', en: 'Noumea', fr: 'Nouméa' },
    'Pacific/Pago_Pago': { ar: 'باغو باغو', en: 'Pago Pago', fr: 'Pago Pago' },
    'Pacific/Palau': { ar: 'بالاو', en: 'Palau', fr: 'Palaos' },
    'Pacific/Pitcairn': { ar: 'بيتكيرن', en: 'Pitcairn', fr: 'Pitcairn' },
    'Pacific/Pohnpei': { ar: 'بونبي', en: 'Pohnpei', fr: 'Pohnpei' },
    'Pacific/Port_Moresby': { ar: 'بورت مورسبي', en: 'Port Moresby', fr: 'Port Moresby' },
    'Pacific/Rarotonga': { ar: 'راروتونغا', en: 'Rarotonga', fr: 'Rarotonga' },
    'Pacific/Saipan': { ar: 'سايبان', en: 'Saipan', fr: 'Saipan' },
    'Pacific/Tahiti': { ar: 'تاهيتي', en: 'Tahiti', fr: 'Tahiti' },
    'Pacific/Tarawa': { ar: 'تاراوا', en: 'Tarawa', fr: 'Tarawa' },
    'Pacific/Tongatapu': { ar: 'تونغاتابو', en: 'Tongatapu', fr: 'Tongatapu' },
    'Pacific/Wake': { ar: 'ويك', en: 'Wake', fr: 'Wake' },
    'Pacific/Wallis': { ar: 'واليس', en: 'Wallis', fr: 'Wallis' },
    
    // UTC
    'UTC': { ar: 'التوقيت العالمي المنسق', en: 'UTC', fr: 'UTC' }
};

/**
 * Get timezone name in specified language
 * @param {string} timezone - IANA timezone identifier
 * @param {string} language - Language code (ar, en, fr)
 * @returns {string} Timezone name
 */
export const getTimezoneName = (timezone, language = 'ar') => {
    return TIMEZONE_NAMES[timezone]?.[language] || timezone.replace(/_/g, ' ');
};
